### ISSUE TITLE
Image Search Bug?

### ISSUE THREAD

**Issue by nikue** [filestack/filestack-js#1]
Can't seem to type anything in the Image Search input field. Everything else seems to work nicely.

API V3/Chrome v56+

**Comment by cogKnitter** [comment]
Hi @nikue can you provide steps to replicate?

**Comment by nikue** [comment]
Nothing special, just using the following:
`client.pick({
			accept: 'image/*',
			fromSources: ['imagesearch','local_file_system','facebook','instagram']
        });`

**Comment by cogKnitter** [comment]
Are you using any css framework in conjunction with filestack-js?

**Comment by nikue** [comment]
Indeed, hence the read out :)

Bootstrap v3

Nikue Gardner

**Comment by cogKnitter** [comment]
Even with bootstrap I'm unable to replicate this issue.
Are you using the latest version of filestack-js?

**Comment by nikue** [comment]
Yes. I even swapped back to Filestack APIv2 today to see if that was still
working. No problems there, using the equivalent picker options. I'll try
and attach some comparative video here when I have a chance. Very odd
behaviour. Perhaps we can just leave this open as a bug for now and see if
anyone else has a similar experience?

**Comment by nikue** [comment]
I've narrowed down the problem. It only occurs when launched from a Bootstrap modal. Here's a fiddle:

https://jsfiddle.net/6hrxdkkn/6/

(just need to enter an api key)

**Comment by velveteer** [comment]
This was reported again with steps to reproduce in #64.
