### ISSUE TITLE
Difference between filestack.js and filestack.es2015.js

### ISSUE THREAD

**Issue by ZeroCho** [filestack/filestack-js#10]
It is quite confusing. In `dist` folder, there's two javascript files.

If I import filestack-js like below, which file does it imports? filestack.js or filestack.es2015.js?
`import filestack from 'filestack-js'`

If it imports filestack.js, how can i import filestack.es2015.js?

**Comment by zimme** [comment]
It seems like `filestack.es2015.js` is used in `js:next` and `module` and `filestack.js` is used in `main`.

So depending on your build system for your app it might use one or the other but I'm pretty sure that unless you use some of the newer build systems for your app like rollup you'll be using `filestack.js´ via `main` in `package.json`.

**Comment by velveteer** [comment]
@zimme Is correct. We are shipping a UMD module and a ES2015 module depending on the appropriate build system. I updated the readme to make this a little more apparent. 

@ZeroCho https://github.com/rollup/rollup/wiki/pkg.module
