### ISSUE TITLE
'filename' option is not working

### ISSUE THREAD

**Issue by ShaunakP** [filestack/filestack-js#103]
Using 1.0.0-rc1 filepicker with our S3 storage option provided, the `filename` option does not seem to modify the name of the file that is uploaded in our S3 bucket. File is uploaded but the name remains as it is in our S3 bucket. 

Alternatively, we also tried setting value of `storeTo` -> `path` as '/buyer/temp.xlsx' but then the original excel file name was getting appended to provided path '/buyer/temp.xlsxuploadedfile.xlsx'

 ```
var options = {
     concurrency: 1,
     disableStorageKey: true,
     disableTransformer: true,
     maxFiles: 1,
     maxSize: 10485760,
     minFiles: 1,
     allowManualRetry: true,
     storeTo: {
         location: 's3',
         path: '/buyer/',
         region: 'us-west-2',
         access: 'private',
         container: 's3-bucket-temp',
         filename: 'temp.xlsx'
     },
     uploadInBackground: false,
     onOpen: function () { },
     onUploadDone: function (response) { },
     onCancel: function () { }
 };
 var client = filestack.init('apikey', {security: { policy:'policy', signature: 'signature' }});
 client.picker(options);
 client.open();
```

Please look into this.

**Comment by velveteer** [comment]
Hey @ShaunakP, sorry for the delay on this, I've been out on vacation for the past week. So this looks like a curious case, I will see if I can address it in parts:

1. The [filename](https://filestack.github.io/filestack-js/interfaces/storeoptions.html#filename) field in the StoreOptions interface is correct but the interface is being incorrectly used in the picker storeTo options. There is no storeTo.filename option for the picker, so this interface and its documentation need to be corrected.

2. Your combination of `disableStorageKey: true` and trying to specify the filename in the path will cause a redundancy. The option assumes that storeTo.path will be a folder. This can also be documented better.

3. The preferred way to rename files in the picker is to use the `onFileSelected` callback and return a mutated file object. See the example here: https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#onfileselected. 

The `storeTo` option needs more clarification, especially the fact that it does not change its behavior when `maxFiles` is 1. It is setting storage options for all picked files, which means a path should be a folder (trailing slash), and if the `filename` field was respected it would rename all picked files to the same string. This is the reason we give access to the filename in the selection event.

I will update the documentation and create a new PickerStoreOptions interface to clarify those options.

**Comment by ShaunakP** [comment]
@velveteer Thanks for giving us all the details. The example [here](https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#onfileselected) makes total sense now. Thanks a ton!
