### ISSUE TITLE
Upload a buffer

### ISSUE THREAD

**Issue by mintyPT** [filestack/filestack-js#106]
When using the upload method from nodejs, I'd like to pass a buffer but all I can pass is a file. 

Is this correct?

**Comment by velveteer** [comment]
At the moment this is correct, the upload method treats the file argument as a file-system path. I believe passing a Node buffer should be an option, so I will mark this issue as an enhancement. The Node implementation is already dealing with buffers under the hood, so it should be somewhat trivial to accept buffers directly.

**Comment by mintyPT** [comment]
That was my understanding of things too. Honestly, I would do a pull request but I never did any typescript so I have no idea how to setup the required tooling.

**Comment by alekbarszczewski** [comment]
For me missing option to upload a buffer is a blocker. My app (Node.js) generates some files in memory that I would like to upload to Filestack without storing it on application server.

**Comment by pcholuj** [comment]
Check newest release 1.5.0, now its supporting uploading using buffers.
