### ISSUE TITLE
Image Transformation :: Crop 

### ISSUE THREAD

**Issue by ghost** [filestack/filestack-js#108]
Hey,

Need clarification.

I would like to display image `upload by`, `description` and `caption` on top of picker or somewhere on the screen (pulled from our server based on the FS imageID) after clicking the crop button (Crop UI). Any method which will let the user/dev take control of image change or as soon as transformation screen shows up?

Looking for something like `onFileUploadStarted`, which gives the item object. I don`t see any on the documentation/API section.

Regards
Hariram

**Comment by maryfs** [comment]
Hi,
unfortunately it's impossible in current version.
