### ISSUE TITLE
Cannot get Facebook to work all the time in Safari

### ISSUE THREAD

**Issue by winzig** [filestack/filestack-js#109]
I am testing the Facebook capability of the file picker, and though my colleagues are able to get it to work, and I can get it to work in Safari private browsing mode, I cannot currently get it to work when in normal browsing mode. I'm trying to figure out how to debug the issue, so that I can help customers that will inevitably run into a similar issue. 

The flow I see is that I select the facebook option, I click to Connect to facebook, Facebook asks me if I want to approve, I confirm yes on everything, and then the tab closes and returns me to the one with the file picker. I can see the file picker view refresh as if it's expecting to be able to connect to Facebook, but nothing changes. The button to connect is still present. I don't see any errors in the dev console or networking pane of Safari. 

Since I can get it to work when in private browsing mode in Safari, I assume there is some cookie or local storage data that is mucking things up, but not clear on what and perhaps this is a bug that can be fixed? 

Note: it's not an issue with our site, because I get the same behavior when using the [demo file picker on Filestack's website](https://www.filestack.com/features/file-uploader).

**Comment by winzig** [comment]
How does one determine if we're using a pre-1.0 or 1.0 version? The release versions here show the latest is 0.11.2, from January. When was 1.0 released?

In terms of the issue itself, after having experienced it for several weeks, tonight I went in on the same browser on Filestack's demo picker, and the Facebook connection is now working. I'm not sure if it's related to the 1.0 change you're talking about, or if something got updated within my browsing session.

**Comment by velveteer** [comment]
I apologize, the changelog in this repo needs a proper updating since we published the 1.0.0 release candidate. #101 

If you are on 0.11.2 (the latest pre-1.0 being 0.11.5) then the client and API are using cookies. Sounds like your issue possibly resolved itself, but if you can reproduce it again try upgrading to 1.0.0 and see if that helps any.

**Comment by winzig** [comment]
Actually, I had forgotten we switched from building from here, to just loading https://static.filestackapi.com/v3/filestack.js directly. I assume that version being served there is the latest release (looking at the file it says version 0.11.5, so sounds like, yes). I'll go ahead and close this out then. Not sure what happened!
