### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by bidva** [filestack/filestack-js#113]
I'm trying to upload a base64 string but I have this error 

`Error: ENAMETOOLONG: name too long, open 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC0AAD/4gxYSUNDX1BST0ZJTEUAAQEAAAxITGlubwIQAABtbnRyUkdCIFhZWiAHzgACAAkABgAxAABhY3NwTVNGVAAAAABJRUMgc1JHQgAAAAAAAAAAAAAA...`

and here is my function 

const token = {};

```
var fs = require('filestack-js');

const onProgress = (evt) => {
  console.log('Progress: ' + evt.totalPercent);
};
async function updateDriverPhoto(req, res){
  let applicationId = req.body.data.attributes.ids[0];
  let attrs = req.body.data.attributes.values;
  let file = attrs['file'];
  fs.init(process.env.FILESTACK_API_KEY).upload(file, { onProgress }, { filename: 'driver.jpg' }, token)
      .then(res => {
        console.log('success: ', res)
      })
      .catch(err => {
        console.log(err)
      });
}
```
I tested my string and seems it's well encoded 
any idea where is the issue ?
seems getFile(fileOrString) in upload.ts just using fs to read from source file  
PS: I don't have access to path of the file , I only have the base64 string version of the file

**Comment by velveteer** [comment]
The upload method has a different API between Node and browser environments. The file argument is treated as a string path, so using a base64 string is not supported. This will probably change soon as we intend to add support for uploading Node buffers, so we can look into adding support for base64 strings in Node as well.
