### ISSUE TITLE
onFileUploadProgress callback not being passed the event parameter

### ISSUE THREAD

**Issue by zacbraddy** [filestack/filestack-js#118]
Hi there

I'm trying to use the `onFileUploadProgress` callback on the options I'm sending to the file picker and I'm finding that the progress callback is being called as expect but it only has the `file` parameter populated. I've written a basic test page here to replicate the problem:

```html
<html>
    <body>
        <script src="https://static.filestackapi.com/filestack-js/1.0.1/filestack.min.js"></script>
        <script>
            const filestackApiKey = "";
            this.client = filestack.init(filestackApiKey);
            let picker = null;

            const opts = {
                accept: "video/*",
                fromSources: [
                    "video",
                    "webcam",
                    "local_file_system"
                ],
                videoResolution: "640x480",
                minFiles: 1,
                maxFiles: 1,
                uploadInBackground: false,
                onFileUploadStarted: (file) => {
                    console.log("onFileUploadStarted");
                },
                onFileUploadProgress: (file, progressEvent) => {
                    console.log("file: ", file);
                    // This should be populated, yet it is not :(
                    console.log("progressEvent: ", progressEvent);
                },
                onFileUploadFinished: (file) => {
                    console.log("onFileUploadFinished");
                },
                onFileUploadFailed: (file, error) => {
                    console.log("file", file);
                    console.log("error", error);
                },
            };

            picker = this.client.picker(opts);
            picker.open();
        </script>
    </body>
</html>
```

Please note I've scrubbed my api key so that's not the reason this is failing 😛 

You can see from the code I'm attempting to do this with 1.0.1 in the latest chrome, just to see if it was browser related I tested it in the latest Firefox too but got the same results.

It's also not the fact that it's running in a local file as the problem arose in my react project which is hosted on a local server. I've just distilled the problem out to a snippet for reporting is all.

I'm expecting that the progressEvent be populated with the FSProgress event as per the documentation [here](https://filestack.github.io/filestack-js/interfaces/pickerfileprogresscallback.html)

Also if it's relevant I'm using my integrated webcam to take a short video ~5 seconds or so and then uploading that.

**Comment by velveteer** [comment]
@zacbraddy Thanks for this detailed report! I believe this is related to the fact that we do not report progress for files uploaded through the Cloud API (i.e. non-local files). This is kind of mentioned in passing in the documentation for [onFileUploadProgress](https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#onfileuploadprogress). Reporting progress for cloud uploads has been a somewhat common feature request, but the current API implementation makes it unlikely that this will happen anytime soon. 

For UX purposes we use an indeterminate progress implementation in the picker for these non-local files, but these events are not exposed in the callback as you've noticed. We could look into exposing this, but it's not meaningful as an actual progress measurement. In any case, the documentation should be updated to make this clearer.

**Comment by zacbraddy** [comment]
Hey, thanks for getting back so quickly. Just in case it's not 100% clear the onFileUploadProgress callback IS being called it's just that the event parameter is not being populated.

If what you're saying is that this is expected behaviour then what is the intended use of onFileUploadProgress is it supposed to just be a heartbeat or something like that?

**Comment by velveteer** [comment]
I think we understand each other. To clarify, for local files the progress event is passed and represents actual upload progress. For non-local files the progress event is not passed. This is the part that is not documented clearly. If we passed the progress event for non-local files we could populate `totalPercent` but it would not be derived from `totalBytes` (which would always be zero for non-local files). 

The common use case for this callback appears to be hampered by the fact that determinate progress is only reported for local files. If we expose our own indeterminate progress for non-local files then the callback would be more suitable for driving your own progress implementation. So I will look into how we can make that better.

**Comment by zacbraddy** [comment]
Oh ok, well if you could do that I'd be very appreciative. Thanks so much for your time.

**Comment by pcholuj** [comment]
Hi, we added fake progress object to cloud progress event in new verson
