### ISSUE TITLE
Webcam option not shown on desktop when window is small

### ISSUE THREAD

**Issue by schmich** [filestack/filestack-js#119]
I am specifying `webcam` as one of the `fromSources` with the picker. This works well on mobile (it opens the device menu) as well as on desktop with a large window (the "Take Photo" option is present and uses the attached webcam).

When I resize the window to be small enough (~980px), the picker modal layout changes responsively, but when I click the "Select From" hamburger menu in the top left, the "Take Photo" option disappears. I would still expect this option to be available on desktop even though the window is small.

A simple repro is available at https://codepen.io/anon/pen/vrgrWX with a demonstration of the issue at https://imgur.com/a/6I6t1lx. Clicking the "My Device" option in that demo just opens the native file open dialog. It does not give a webcam option.

I debugged into this a little. The file source visibility in the modal is determined partly in https://static.filestackapi.com/picker/src/components/SourceNavItem.vue:

```js
isHiddenOnMobile() {
  return this.mobileNavActive &&
    (this.sourceName === 'webcam'
      || this.sourceName === 'video'
      || this.sourceName === 'audio');
},
```

No problem, it looks like the `webcam`/`video`/`audio` option is hidden on mobile since you use the device menu instead. When I first load the modal on desktop with a small window, this returns false for all options, so it thinks `this.mobileNavActive` is always false.

`mobileNavActive` is initialized in https://static.filestackapi.com/picker/src/store/store.js:

```js
mobileNavActive: checkMobile(navigator.userAgent),
```

`checkMobile` just looks at the user agent string:

```js
export default (obj) => {
  const isMobileDevice = new RegExp('Android|webOS|iPhone|iPad|BlackBerry|Windows Phone|Opera Mini|IEMobile|Mobile', 'i');
  return isMobileDevice.test(obj);
};
```

In my case, this is `false` (which is correct) since my user agent is "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36".

Now, when the window is small and I go to click on the top left hamburger menu to open and see the available sources, `mobileNavActive` gets updated in `toggleNav` in  https://static.filestackapi.com/picker/src/components/MobileMenuButton.vue:

```js
export default {
  computed: {
    ...vuex.mapGetters(['mobileNavActive', 'route']),
    hideLocalOnMobile() {
      const newRouteHistory = clone(this.route);
      const lastRoute = newRouteHistory.pop();
      if (checkMobile(navigator.userAgent) && lastRoute.indexOf('local_file_system') !== -1) {
        return true;
      }
      return !this.mobileNavActive;
    },
  },
  methods: {
    ...vuex.mapActions(['updateMobileNavActive']),
    toggleNav() {
      this.updateMobileNavActive(this.hideLocalOnMobile);
    },
  },
};
```

In my case, `this.hideLocalOnMobile` is returning `true` because of the `return !this.mobileNavActive;`. With `mobileNavActive` now `true`, the `isHiddenOnMobile` gets re-evaluated for each source, which ultimately ends up hiding the `webcam` source.

I'm not sure what the root cause is or what the fix is, but unless I'm missing something, this seems like a bug. Even with a small window on desktop, I imagine the webcam source should still be visible.

**Comment by velveteer** [comment]
@schmich I believe this is related to how pre-1.0 versions handle mobile detection. Can you attempt reproducing on a 1.0 release? If it's still an issue on the latest version then it's probably a bug, since we should be showing all sources in the menu regardless of screen size or user agent.

**Comment by schmich** [comment]
@velveteer Thanks. With an updated library reference (https://static.filestackapi.com/filestack-js/1.x.x/filestack.min.js), this appears to be fixed.

I'm still a bit confused on the various versions of the Filestack API, however. According to the [Getting Started Guide](https://www.filestack.com/docs/getting-started), it recommends developers to use `<script src="https://static.filestackapi.com/v3/filestack.js"></script>`, which has "v0.11.5" at the top, so I assume this what you mean by "pre-1.0 versions"?

Is the documentation just outdated? Should it be telling developers to use https://static.filestackapi.com/filestack-js/1.x.x/filestack.min.js instead?
