### ISSUE TITLE
Transforming a file on upload

### ISSUE THREAD

**Issue by nikparo** [filestack/filestack-js#120]
This is an enhancement suggestion, as I don't think this is currently possible in one call.

We use the filepicker to let our app users upload images, and we have recently realized that photos sometimes get rotated according to the exif data when viewed on a mobile device. I know that we can specify either `rotate=deg:exif` or `rotate=exif:false` to fix that through a transformation, however, it would be neat to be able to do some transformations on upload, especially if you know that you will never need the original.

Examples:
- Rotate the image according to exif
- Convert the image to JPEG
- Apply a colour filter or convert to grayscale
- Compress the image
- etc.

On that note, I guess the best way to accomplish this today is to upload + store transformation + delete original?

**Comment by neha9t** [comment]
I am looking forward for compress an image option too? Is it possible to compress an image before upload?

**Comment by pcholuj** [comment]
This can be done using workflows https://www.filestack.com/docs/concepts/workflows/
