### ISSUE TITLE
Picker force circle transformation

### ISSUE THREAD

**Issue by sfeldkamp** [filestack/filestack-js#122]
Picker options.transformations.crop.force = true forces the image to be cropped before it is uploaded.

There does not seem to be a way to force a circle transformation before the image is uploaded.  

**Use Case:**

We are collecting an image to use as an _avatar_ style logo.  In order for this circle crop to look good the user needs to be able to size and place the circle crop on the picked image.

Is there a way to do this either with the picker or with the api otherwise?

**Comment by AllanPooley** [comment]
Hey @sfeldkamp,

👍 +1 to this issue, I've got the exact same use case in my web app.

In the mean time, I will be using:

```
pickerOptions = {
  accept: 'image/jpeg',
  transformations: {
    crop: {
      aspectRatio: 1,
      force: true
    }
  }
};
```

This forces a perfect square (equal height and width), such that the user only loses the part of the image clipped by the circular border radius.

**Comment by pcholuj** [comment]
Hi in v 3.0.0 you can pass transormations : { force: true, circle: true, crop: false} now

**Comment by bkroeker** [comment]
@pcholuj Can you please confirm what the correct way to force a circle transformation is?  

The documentation does not mention any force option here: https://www.filestack.com/docs/concepts/pickers/web/#transformation-options

But it is mentioned here:
https://filestack.github.io/filestack-js/interfaces/pickertransformationoptions.html

But I get a JS error when I try this:
```
filestack_client.picker({transformations: {force: true, circle: true, crop: false}}).open()
// Throws: Error: Unknown config option "transformations.force"
```

**Comment by bkroeker** [comment]
I found the problem.  I'm using the filestack-rails gem, and when you set it to use "v3", it's importing //static.filestackapi.com/filestack-js/1.x.x/filestack.min.js instead of //static.filestackapi.com/filestack-js/3.x.x/filestack.min.js.  When I manually load 3.x.x, then it works.
