### ISSUE TITLE
Parcel doesn't recognize "browser" key

### ISSUE THREAD

**Issue by andreyvital** [filestack/filestack-js#124]
We're having an issue that, recently you guys introduced this new `browser` key in the **package.json**:
https://github.com/filestack/filestack-js/blob/master/package.json#L7.

Problem is, it may work for webpack but doesn't actually work with [Parcel](https://parceljs.org/). Is there any way to solve this without rewriting the package.json every **postinstall**?

```JS
(...)

const filestackPackageJson = path.resolve(
  __dirname,
  "..",
  "node_modules",
  "filestack-js",
  "package.json",
);

const packageJson = require(filestackPackageJson);

// parcel doesn't understand "browser" key in package.json
packageJson.main = packageJson.browser;

fs.writeFileSync(filestackPackageJson, JSON.stringify(packageJson, null, 2));

(...)
```

**Comment by velveteer** [comment]
@CentaurWarchief Parcel does support the `browser` property, and I can successfully bundle the browser ES module with the following:

index.html

```html
<html>
<body>
  <script src="./index.js"></script>
</body>
</html>
```

index.js
```js
import * as filestack from 'filestack-js';

const client = filestack.init('abc');
client.picker().open(); // this works only in browsers
```
Using Parcel v1.9.4 and filestack-js 1.2.1

We can help more if you provide exact steps to reproduce the problem you are having.

**Comment by CentaurWarchief** [comment]
@velveteer we're using it along with `filestack-react`. Does it work same way? Since parcel doesn't understand the `browser` package.json property, how could it load the proper js bundle? Here it's loading the node bundle, and trying to call `fs.open`

**Comment by CentaurWarchief** [comment]
It's not using filestack-js, but here's a quick demo that loads `node.js` rather than `browser.js` (parcel doesn't read the "browser" key)

<img width="566" alt="screen shot 2018-07-09 at 14 50 03" src="https://user-images.githubusercontent.com/967317/42467144-78db226c-8387-11e8-9f1c-62521fc70ace.png">

The same happens for this library. Maybe there's a better way to "fix it" rather than a `postinstall` "hack"?

**Comment by pcholuj** [comment]
Hi 
I see that Parcel added support for browser kay in package.json (https://github.com/parcel-bundler/parcel/issues/1883)

Is it still an issue?
