### ISSUE TITLE
Clicking on 'Select Files to Open' does nothing

### ISSUE THREAD

**Issue by billscheidel** [filestack/filestack-js#13]
I'm using v3 FileStack v0.5.2.  On the dialog that opens, it says 'Select Files To Upload'.  I assumed this meant that if I clicked on that, a Windows dialog would open allowing me to select a file.  However, clicking on it doesn't seem to do anything and produces no error.  Is it supposed to do something?

**Comment by cogKnitter** [comment]
Hi Bill. I would definitely recommend updating to v0.6.0.
When you click 'Select Files To Upload' do you get any console errors?

**Comment by billscheidel** [comment]
Looks like it is working fine in v0.6.0.  Thanks!
