### ISSUE TITLE
Catch invalid policy and signature

### ISSUE THREAD

**Issue by mixalistzikas** [filestack/filestack-js#131]
this.client = filestack.init('apiKey', {security: { 'policy': 'policy-key', 'signature': 'signature-key' }});

    const options = {
         fromSources: ['local_file_system', 'dropbox'],
         maxFiles: 20,
         uploadInBackground: false,
         onOpen: () => console.log('opened!'),
         onUploadDone: (res) => console.log(res),
      };
      this.client.picker(options).open();

I have this code and I don't know how can I catch an error at policy or signature (wrong keys). When I click the button that triggers picker().open() it makes an api call at https://cloud.filestackapi.com/folder/list and returns 404 error and the filestack picker open without any error message.

**Comment by pcholuj** [comment]
we cant do that for now.
