### ISSUE TITLE
cropped is not passed when forcing crop on picker

### ISSUE THREAD

**Issue by asafigan** [filestack/filestack-js#132]
transformations is:
```
crop: {
  force: true,
  aspectRatio: 1
}
```
fileMetaData doesn't have cropped data unless user resized the crop area. Not even moving the crop area fixes the problem.

**Comment by asafigan** [comment]
The reason I need this data is that I need to retransform the image to display it in a form. The reason that I can't use the url provided is because I have security enabled and therefore downloading it is blocked. The best option would be for filestack-js to include the dataurl of the uploaded image(transformed) in the fileMetaData. But I am fine with just fixing this issue so that I can do it myself.

**Comment by pcholuj** [comment]
Hi, if i good understood, you want to have cropped file data before user will upload it? Ie just after crop? 

We can expose file data url in all callbacks, its a good idea so everyone can manipulate the file on their own. ie put it as a thumb before it will be uploaded.

**Comment by pcholuj** [comment]
Fixed in https://github.com/filestack/filestack-js/tree/v3.5.0
