### ISSUE TITLE
Picker wont open in production

### ISSUE THREAD

**Issue by llamle** [filestack/filestack-js#133]
Hi all,

This is a React app (16.2), using webpack 4.3, filestack-js 1.4.1, and filestack-react 2.0.0.

When I click to open the file picker I get the following error:

![image](https://user-images.githubusercontent.com/12277292/43417428-f1ce9104-9408-11e8-96d5-bd71e428aa0d.png)

I saw this issue: https://github.com/filestack/filestack-react/issues/19 and attempted to exclude filestack-js from minification in my webpack setup, but that didnt help. I also tried to set the import path to the source file, also did not help.

Does anyone know what the solution to this is?

Thank you.

**Comment by christine64** [comment]
Hi, I would like to ask whether you found a resolution for this issue?

**Comment by pcholuj** [comment]
@christine64 can you provide more info about this bug?
What version of fielstack-react and filestack-js are you using ?

**Comment by christine64** [comment]
Hi pcholuj,

I was using the latest filestack-react and filestack-js, running with react 16.3.2, it appears it was compiling successfully when it was unbundled in dev environment, however when moving it into an env where UglifyJsPlugin was used to minify the source code, it appears to again minify this, it would break the modal once it had opened with a message of `This application is unavailable`, and display a message of `n is not a function`.

![Screen Shot 2020-11-17 at 7 40 53 pm](https://user-images.githubusercontent.com/13471148/99366801-3676c880-290d-11eb-9a33-65106f7d2d52.png)

**Comment by akshaybandivadekar** [comment]
> Hi pcholuj,
> 
> I was using the latest filestack-react and filestack-js, running with react 16.3.2, it appears it was compiling successfully when it was unbundled in dev environment, however when moving it into an env where UglifyJsPlugin (webpack 3) was used to minify the source code, it appears to again minify this, it would break the modal once it had opened with a message of `This application is unavailable`, and display a message of `n is not a function`.
> 
> ![Screen Shot 2020-11-17 at 7 40 53 pm](https://user-images.githubusercontent.com/13471148/99366801-3676c880-290d-11eb-9a33-65106f7d2d52.png)

@christine64 Have you get a solution to fix this issue?

**Comment by christine64** [comment]
Hi @akshaybandivadekar,

Unfortunately I didn’t get it working with filestack-react, I resorted to just using file stack-js, which is just as simple to use without this package. 
If you’re trying to bundle if for a production environment I would avoid this package and directly use filestack-js.

**Comment by akshaybandivadekar** [comment]
Hi @christine64 

Thanks for the reply.
I am currently using filestack-js npm package with version 3.21.0, seems an issue with version 3 only, once we downgrade to v2 then it's works
