### ISSUE TITLE
Rename the file

### ISSUE THREAD

**Issue by ddancy** [filestack/filestack-js#134]
Can we change the file name before upload? Especially for multiple uploads. For some reason, I need to auto change the special character in the file name before upload. But I can't find a way to do this. Does filestack support this function?

**Comment by velveteer** [comment]
For renaming files in the picker please look at https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#onfileselected

**Comment by martijnvdbrug** [comment]
The correct link to the docs now seems to be https://filestack.github.io/filestack-js/interfaces/PickerOptions.html#onFileSelected

Also, I had to make the example async, otherwise file rename did not work!

```diff
  client.picker({
-       onFileSelected: (file) => { 
+      onFileSelected: async (file) => {
        const name = `${props.orderLineNumber}_${props.variantName}_${file.filename}`;
        console.log(`Uploading to '${props.orderCode}/${name}'`);
        return { ...file, name };
      },
    })
    .open();

```
