### ISSUE TITLE
Allow cloud sources and url source to be used without store.

### ISSUE THREAD

**Issue by asafigan** [filestack/filestack-js#135]
I had a lot of trouble debugging errors caused by not having storage set up and trying to use these other sources. Is there a way to just use some default behavior for these sources without having to have a storage target? Also can you configure the storage of the intermediate file (the one selected by the user, but not the final transformed image) separately? 

I also tried using `preferLinkOverStore` but I am still getting errors. What exactly does that option do?

**Comment by maryfs** [comment]
Hi,
do you still getting errors for v. 2.x.x?
