### ISSUE TITLE
Cannot find module 'filestack-js' using angular cli

### ISSUE THREAD

**Issue by cesarcastmore** [filestack/filestack-js#14]
I have been developing an app using angular cli but I have the error:
Cannot find module 'filestack-js'

First I install the filestack
npm install --save filestack-js

Second I add a line in script to the file angular-cli.js
   "scripts": [
          "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "../node_modules/filestack-js/dist/filestack.js"      ],

Third, I add the line import 
import filestack from 'filestack-js';

When I run my server I have the error "Cannot find module 'filestack-js'"

**Comment by velveteer** [comment]
@cesarcastmore I am unfamiliar with angular-cli, but it appears that the `scripts` configuration is for global scripts. I am not sure how the ES `import` syntax is being interpreted here, i.e. I don't know how the code is being bundled. 

How are you referencing jQuery and Bootstrap in your code? Are you using `import` syntax for those too?

**Comment by cesarcastmore** [comment]
Hello @velveteer 

I am reading the website to solve my error
https://www.typescriptlang.org/docs/handbook/module-resolution.html

I run the following command
tsc --moduleResolution node src/app/content/ventas-instapics/ventas-instapics.component.ts

I have the lines
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(28,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(87,123): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(87,165): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Set'.
node_modules/rxjs/Observable.d.ts(69,60): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
src/app/content/ventas-instapics/ventas-instapics.component.ts(2,23): error TS2307: Cannot find module 'filestack-js'.
src/app/content/ventas-instapics/ventas-instapics.component.ts(9,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning

I am not sure what it mean these lines, but I looked for the file with extension map  and I didn't find.

**Comment by cesarcastmore** [comment]
Hello

Do you have a example using webpack?
https://webpack.github.io
