### ISSUE TITLE
Upload goes into an infinite spinner with unsupported file data

### ISSUE THREAD

**Issue by gpimpler** [filestack/filestack-js#140]
We are currently using version 0.9.12 and experiencing an issue now and then with some customers uploading incorrect files.  We are using the filepicker component to allow user to upload files.  Every once in a while a user submits a file that has different content than what it should.  We would like for this to error and let the user know that there is a problem with the file but we do not get anything back to facilitate that messaging. 

<img width="806" alt="screenshot 2018-08-21 16 02 27" src="https://user-images.githubusercontent.com/1474285/44428996-b3af0980-a55b-11e8-9443-5b9155cdc5a6.png">

To test this, create an html document such as test.html with a little data in it (i.e `<html></html>`, **then rename that file to something such as test.png**).  It is now a file that FS believes to be an image but it is truly just html data.  Once you upload this file, the application just spins infinitely.  We can see the onFileSelected() event fire, but nothing beyond that fires.  No error ever comes back, it doesn't appear to timeout and onRetry() did not fire.  We even tried throwing an error inside of the onFileSelected() function if a certain amount of time had passed, but nothing.  If we emitted an error immediately when that function was invoked, it did error out and present the error but it had to be immediate, else the error could be seen in the console but the file picker would not respond accordingly.  Unfortunately the file data that gets passed into onFileSelected(obj) did not provide any information that we could trigger an error on immediately since it thinks it's valid data as well.  Any help here would be appreciated.  Maybe we are just missing something but even the sample application in our account portal just spins infinitely as well.

**Comment by maryfs** [comment]
Hi, could you try to use newer version ( like 2.x.x) ? i cannot reproduce it on newer version.
