### ISSUE TITLE
File uplaoded callback not being passed parameter in Firefox

### ISSUE THREAD

**Issue by jakemor** [filestack/filestack-js#141]
The event parameter is not populated on Firefox:

``
<input id="file-upload-button" type="filepicker" data-fp-apikey="A1nL8omiAR8W7pHi3cotzz" data-fp-mimetypes="*/*" data-fp-container="modal" data-fp-multiple="true" data-fp-maxsize="10000000" data-fp-services="COMPUTER,DROPBOX,URL,GOOGLE_DRIVE,GMAIL,VIDEO,WEBCAM" onchange="fileUploaded(event)">
``
Any idea what's going on? Works in chrome...

**Comment by pcholuj** [comment]
Hi, is this issue still occurs in new filestack-js ?
