### ISSUE TITLE
storeTo: issues with crop

### ISSUE THREAD

**Issue by lbarbula** [filestack/filestack-js#143]
I am attempting to use the store to property with the crop method. It's the same config that I use for upload. Using it immediately breaks the modal with the following symptoms.

<img width="309" alt="screen shot 2018-09-04 at 2 22 02 pm" src="https://user-images.githubusercontent.com/16232100/45055742-f38eea00-b04d-11e8-859f-a147f309d3a9.png">

The src tag for the image in the modal that I was attempting to crop was undefined. 

My storeTo object looks like this:
storeTo: {
        location: 'rackspace',
        path: '/upload/',
        container: 'api_test'
      },

This appears to be a bug of some kind, as it appears that this all lines up with the PickerStoreOptions object.

I have gone property by property through the picker options, and this is the one that causes a failure. Changing the location to s3 causes the issue to go away, but that doesn't help me, because that is not what I am using for storage.

Here is a link to the slightly adapted jsfiddle that I have been using to test. The api key has been removed. http://jsfiddle.net/6Ltd4am3/14/

**Comment by lbarbula** [comment]
Did anyone find a way to resolve this?

**Comment by TCWIreland** [comment]
No filestack have not fixed it. I went to uploadcare - brilliant service.

**Comment by pcholuj** [comment]
Hi. Its more complicated problem related to rackspace. We are trying to resolve it right now.

**Comment by maryfs** [comment]
Hi, @lbarbula  could you verify if problem still exists?
We have released some changes which should help.
Also, use version 2.x.x and let us know.
Thanks.

**Comment by celloman** [comment]
Hi @maryfs Lucas' co-worker here. We just tried the 2.1.0 release and still encountered the same issue.

**Comment by maryfs** [comment]
Hi @celloman 
i tested it with fiddle http://jsfiddle.net/6Ltd4am3/14/  using my rackspace, with version 2.1.0 and latest 2.6.0 and it works for me, could you please contact our support? We need your apikey to reproduce it.

**Comment by celloman** [comment]
Hi @maryfs you are totally correct, my bad. We had added a 'region' argument of 'ORD' to the storage setup in our test to see if that helped and that made it look like it was still broken, it appears that the new release has fixed this problem! Thank you!
