### ISSUE TITLE
errors messages in the picker disappear to soon

### ISSUE THREAD

**Issue by GordonGuenther** [filestack/filestack-js#147]
I would like to request a picker option to set a display duration until error messages will disappear automatically.

As far as I know, there is no such option right now and the messages will disappear after around 5 seconds. That is fine for most use cases. But sometimes, when you have very long error messages, 5 seconds will be too short to read the whole message. For example, if you use a very long list of accepted mimetypes, this list will be used within the error message of 'pageAsked'.

So setting a higher display duration or even disabling the automatic disappearing would be a much-appreciated feature.

**Comment by kbluescode** [comment]
Running into this myself. It's quite difficult to style in development too since the errors disappear so quickly.

**Comment by pcholuj** [comment]
Hi in version 3.0.0 we increased it to 8sec. Is it ok ?

**Comment by kbluescode** [comment]
@pcholuj is there a way we could configure this timing ourselves?

**Comment by pcholuj** [comment]
Ok :) i will add this option in next release. Default value for errrorsTimeout option will be 8000ms

**Comment by pcholuj** [comment]
Released in v3.1.0
