### ISSUE TITLE
Crop false transformation option does not work

### ISSUE THREAD

**Issue by danjac** [filestack/filestack-js#148]
I would like to allow only "circle" transformations, for example for avatars. I have the following settings:

      transformations: {
        rotate: false,
        crop: false,
        circle: true
      },
 
However the cropping dialog always has the "crop" button on the left as well as the "circle" option. There does not appear to be any way to remove this, contrary to the docs.

Browser: Firefox 62.

**Comment by danjac** [comment]
Issue also in Chrome.

Fiddle: https://jsfiddle.net/e9ma7Lpr/

**Comment by pcholuj** [comment]
Hi. This should be fixed in 3.0.0 :)
