### ISSUE TITLE
Blank or White screen on Ionic 2

### ISSUE THREAD

**Issue by mrvipinkashyap** [filestack/filestack-js#15]
I am trying to implement filepicker functionality using this library on Ionic 2 app but after importin this library I am getting blank and white screen. This doesn't happen with any other 3rd party library I am using in my app.

Try following steps to reproduce this issue:
Install module using:
`npm install --save filestack-js` 

Import using following code in .ts file:
`import filestack from 'filestack-js';`
Doing `console.dir(filestack);` would show that module has been imported successfully. But you should see that you see blank/white screen if you are running app on `ionic serve`
I also tried following code to check if it is actually working:
```
const apikey = 'MY_FILESTACK_API_KEY';
const client = filestack.init(apikey);
client.pick({
    maxFiles: 20,
    fromSources: ['local_file_system', 'facebook'],
}).then(res => console.log(res));
```
Using above code I was able to see picker but on closing it still see that blank screen. I am not sure whether this is an issue with plugin or Ionic, so I am adding it to both. Please let me know if anyone else has came across similar error and managed to resolve this.

**Comment by maryfs** [comment]
Hi , is this still an issue with version 2.x.x ?
