### ISSUE TITLE
bad uploads: parsing JSON as XML

### ISSUE THREAD

**Issue by asafigan** [filestack/filestack-js#151]
I am getting the following error when trying to upload an Image.

```
XML Parsing Error: no root element found
Location: https://s3.amazonaws.com/filestack-uploads-persist-production/AsvvmUBAFQO6tgZcwqrboz/34jRFenSBqRwH7JgHBG8_mocha_pic.JPG
```

I look at the network request and it looks like the response is json. But the uploader is trying to parse XML.

**Comment by pcholuj** [comment]
Hi this is known problem when uploading to s3 in firefox browser. It happens when s3 returns 200 with no content inside
