### ISSUE TITLE
Make drag-and-drop work even after initial drop

### ISSUE THREAD

**Issue by winzig** [filestack/filestack-js#153]
Right now, when you drag and drop files into the default upload screen, it works, and then shows those files ready to be uploaded. 

It seems logical that a user can grab some more files and drop them onto the same window, but when you try that, it doesn't work. Instead, it just shows that file to the user in their browser. 

Is there a way the picker could be improved so that the drag-and-drop functionality works at all times?

**Comment by winzig** [comment]
Demonstration:

![gifable-185421c4-8f6e-498f-a8b0-b8659f9f23d6](https://user-images.githubusercontent.com/127062/46427894-65169280-c6f7-11e8-9b07-7b08b6623073.gif)

**Comment by velveteer** [comment]
@winzig Check out the `globalDropZone` option: https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#globaldropzone

**Comment by winzig** [comment]
@velveteer Thanks! Classic RTFM moment ;-)
