### ISSUE TITLE
not clear on how you upload more files 

### ISSUE THREAD

**Issue by ansaarYounis** [filestack/filestack-js#154]
We as a company are a print trader and we use filestack for clients to upload files, with session replay we see alot of issues when customer upload one item but wants to upload more. We write messages about upload all files in the window but some client just upload the one file then don't know how to upload more... as you can see that i know how to do it but for our clients its getting more confusing.. can we add a new button next to upload saying 'upload more files' which would open up a new disk window for them to upload more files.. it can be done on a feature switch too that you add to the picker as i suspect all clients of your wont need that

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39402274/46481114-8b692a80-c7ea-11e8-9479-046d51d466f5.gif)

Please let me know

ayounis@tradeprint.co.uk

**Comment by pcholuj** [comment]
Added in newest release
