### ISSUE TITLE
Options for Custom Source default view 

### ISSUE THREAD

**Issue by SteveJamiesonSSN** [filestack/filestack-js#157]
See closed issue,   changes to the default option for custom source view.  

https://github.com/filestack/filestack-js/issues/35

- Would be great if we can pass in a default view option in our picker options object 
- options that would be nice -  set default view to details, set default view to list view, set default to icon view.

**Comment by pcholuj** [comment]
Hi we added "viewType: list|grid" Param to picker options. 
is it ok? for now we are not planning to change other views than "pick file view"
