### ISSUE TITLE
getSecurity function fails on put more than one parameter in call property

### ISSUE THREAD

**Issue by eugeneantonevich** [filestack/filestack-js#158]
I'm trying to generate policy with getSecurity function 

Code:
```
import * as filestack from "filestack-js";
filestack.getSecurity({
   expiry: ...,
   call: [ "store" , "pick" ]   
},
"app_secret"
)
```

and it fails on parameters validation.

file: lib/enums.js
```
  Enums.is = function (x) {
    return map.hasOwnProperty(x);
  };
```

this function receives the following data:
map: { store: "store", ...  other possible parameters }
x: ["store", "pick"]

so, hasOwnProperty function returns false and I receive validation error.

If I send only one value, for example “store”, hasOwnProperty completes with success and i receive generated policy.

Can you explain, if I am calling the function correctly?

**Comment by wcrozier12** [comment]
I am running into this same issue

**Comment by pcholuj** [comment]
Hi this should be fixed in 3.x.x
Current schema for this options is 
```
securityCallDef: {
      id: '/securityCallDef',
      oneOf: [{
        additionalProperties: false,
        type: 'string',
        enum: ['pick', 'read', 'stat', 'write', 'writeUrl', 'store', 'convert', 'remove', 'exif', 'runWorkflow'],
      }, {
        type: 'array',
        additionalProperties: false,
        items: [{
          minItems: 1,
          maxItems: 10,
          type: 'string',
          additionalProperties: false,
          enum: ['pick', 'read', 'stat', 'write', 'writeUrl', 'store', 'convert', 'remove', 'exif', 'runWorkflow'],
        }],
      }],
    },
```
