### ISSUE TITLE
SVG Thumbnails - Custom Source - Picker 

### ISSUE THREAD

**Issue by SteveJamiesonSSN** [filestack/filestack-js#161]
![image](https://user-images.githubusercontent.com/26970903/46756326-9108b980-cc9d-11e8-9c1a-addcd69e3fd3.png)

Custom Source = S3 
Noticing after adding .SVG files that the picker doesn't display a proper thumbnail for the SVG files

**Comment by pcholuj** [comment]
Hi. This should be fixed in newer releases. If you will have problems with it, please contact our support. Thanks!
