### ISSUE TITLE
`customText` option not working for some options.

### ISSUE THREAD

**Issue by juanstiza** [filestack/filestack-js#167]
Hi!

I tried setting one of the custom text messages described in https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#customtext

Here is a fiddle: http://jsfiddle.net/vk4r2jzL/2/

After selecting more than 2 files (the max. files specified), the error shown is still the default one and not the one set on the `customText` property.

Let me know if I am doing something wrong.

**Comment by pcholuj** [comment]
Hi. We will release fix in few days for this

**Comment by pcholuj** [comment]
Fixed in 1.10.0
