### ISSUE TITLE
How to set the MIME type?

### ISSUE THREAD

**Issue by PaulParker** [filestack/filestack-js#171]
I saw this documentation on how to change the file name https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#onfileselected however when I try to set `type` instead of `name` the MIME type is not updated.

Is there a way to change it?

**Comment by winzig** [comment]
@pcholuj Any ideas here?

**Comment by winzig** [comment]
We worked around this problem by moving to AWS ElasticTranscoder for video conversions. This fixed quite a few playback bugs we discovered with videos transcoded by FS.

**Comment by pcholuj** [comment]
Hi. for now you cant change mimetype before upload, but in new version we will have better mimetype checker. With what files you had a problem? Can you provide some examples why u need to change mimetype before upload?
