### ISSUE TITLE
Built module contains es6 const.

### ISSUE THREAD

**Issue by ganmor** [filestack/filestack-js#174]
Our build is failing because the build which is supposed to be es5 contains es6
This is not supported by uglify.

Unexpected token: keyword (const) [./node_modules/filestack-js/build/browser/index.esm.js:11950,0

We could transpile the module with babel but that's definitely not ideal.

**Comment by pcholuj** [comment]
Hi. Can you try to use uglify-es instead of uglify. It has the same interface as old library.

**Comment by ganmor** [comment]
Hi. We ended up using Terser
Although it made use rewrite a large part of our webpack config , it is not a problem for us anymore.

( I don't think it's a good idea to bundle es6 in the browser build though)

**Comment by pcholuj** [comment]
Ok this should be resolved with 2.x.x version, problematic module was replaced

**Comment by IanVS** [comment]
It seems that ES6 is still being used in `build/browser/filestack.esm.js`, which is specified in the `browser` field of package.json.  For the moment I need to support IE11, which can't handle `const`, and webpack doesn't process imports from `browser` it seems (I'm still trying to find a way to force it to).  It seems to just be at the very end of the file:

![image](https://user-images.githubusercontent.com/4616705/71651439-6e701f80-2ceb-11ea-95b2-1e9cf98cb91f.png)
