### ISSUE TITLE
iPad file picker does not show videos, only photos

### ISSUE THREAD

**Issue by winzig** [filestack/filestack-js#175]
When using the file picker on my iPhone running iOS 12.1, I am able to choose either photos or videos via the "My Device" route. I can also "Take a Photo or Video" on the iPhone, and attach it.

But when I am on my iPad (also running iOS 12.1), only photos show up, no videos. And the "Take" option only allows me to shoot a photo, not a video.

How do we resolve this bug?

**Comment by winzig** [comment]
Even though our `accept` parameter specifies many video extensions and this works fine on iPhone, we have discovered that adding 'video/*' to the `accept` list will enable video uploading from iPad. I've reported this to FS support so they can dig in further.

**Comment by maryfs** [comment]
Hi,
thanks for workaround, if its reported on support, we will provide bugfix in future.
