### ISSUE TITLE
Closing the picker modal doesn't cancel the file uploads

### ISSUE THREAD

**Issue by muratakbal** [filestack/filestack-js#18]
Hi,

I realized an issue while testing V3 picker. If there are ongoing uploads when the picker modal is closed, those uploads are not being canceled. 

here is the recording of the issue. http://recordit.co/p353HXOvaw

let me know if you need more info about it.

**Comment by velveteer** [comment]
@muratakbal This is expected, but we will eventually be adding an option to configure this behavior. Thanks for the feedback!

**Comment by muratakbal** [comment]
thx for the quick response. is there a way to cancel the ongoing uploads through the API. I'd like to start using v3 ASAP, but this behavior prevents me from doing that.

**Comment by xcopy** [comment]
@muratakbal, try this:

```js
const client = filestack.init('...'),
   filesStarted = 0,
   filesFinished = 0,
   uploadAborted = false,
   options = {
      // ...
      uploadInBackground: false,
      onFileUploadStarted: function () {
         filesStarted++;
      },
      onFileUploadFinished: function () {
         filesFinished++;
      },
      onClose: function () {
         if (filesFinished < filesStarted) {
            uploadAborted = true;
         }
      }
   };

client.pick(options).then(function (response) {
   if (uploadAborted) {
      // cancel something here
      return false;
   }

   // or do something with response
});
```

Actually this is quick code. You can extend an idea. What you say?

**Comment by velveteer** [comment]
As of 0.8.0 all uploads in progress will be cancelled if the user closes the modal. Hiding the modal via `hideWhenUploading` will not cancel uploads.
