### ISSUE TITLE
Getting a broken link when using client.transform

### ISSUE THREAD

**Issue by harrisrobin** [filestack/filestack-js#180]
Using:

`filestack-js": ^1.8.3`

I get a broken URL when using the following:
```js
const filestackurl = client.transform(IMAGE_ID, {
  resize: {
        width: 500,
        height: 230,
        fit: "crop"
      }
})
```

This yields the following broken URL:
`https://cdn.filestackcontent.com/resize=width:500,height:230,fit:crop/"/E2pWCjyPRtaWtxSAl2sE""`

If i remove the extra `"` at the end and the extra `/"`, this fixes it and i get the desired image.

Has anyone else run into this issue?

**Comment by pcholuj** [comment]
Hi
Can you provide some example values of IMAGE_ID ?

**Comment by harrisrobin** [comment]
@pcholuj you're right, there was a `/` at the beginning that we were passing. My bad. 

Thanks for the help!
