### ISSUE TITLE
Error with getSecurity policyOptions validation

### ISSUE THREAD

**Issue by ryankauk** [filestack/filestack-js#181]
I'm using filestack-js with typescript, and when using the getSecurity method I'm getting a parsing error from the provided param "call". Typescript throws and error if it's not an array because it's type any[].

filestack.getSecurity({
        expiry: Math.floor(new Date().getTime() / 1000) + 20, // expires in 20 seconds
        call: ["pick"],
        maxSize: 1000 * 1000 * 2 // 5 mb
      }, this.filestackApiSecret)

using these params I get error 

Invalid value [
  "pick"
] supplied to "pick" | "read" | "stat" | "write" | "writeUrl" | "store" | "convert" | "remove" | "exif"
    at /Users/ryankauk/Programming/WebStorm/seed-v2/node_modules/filestack-js/build/main/lib/utils/index.js:76:27
    at Array.forEach (<anonymous>)
    at Object.exports.checkOptions (/Users/ryankauk/Programming/WebStorm/seed-v2/node_modules/filestack-js/build/main/lib/utils/index.js:65:13)
    at Object.exports.getSecurity (/Users/ryankauk/Programming/WebStorm/seed-v2/node_modules/filestack-js/build/main/lib/api/security.js:48:13)

The validation is using enum from tcomb-validation against an array which is failing

Test Case:

var t = require('tcomb-validation');
var validate = t.validate;
let enums = t.enums.of('pick read stat write writeUrl store convert remove exif')

let valid = validate(["pick"], enums).isValid() 
// current implementation: will produce false
let valid2 = validate(["pick"], t.list(enums)).isValid()
// valid implementation: will produce true

**Comment by ryankauk** [comment]
Just created a PR for this.

https://github.com/filestack/filestack-js/pull/182

**Comment by pcholuj** [comment]
Thanks for PR. everything is now updated and fixed
