### ISSUE TITLE
Can't use url source when security is enabled

### ISSUE THREAD

**Issue by asafigan** [filestack/filestack-js#186]
I can't use the url source when I have security enabled. The problem is that the uploader stores the original image first than tries to download it from filestack but the policy don't have permission to view that image. We can't give the user a policy that can view all images because then they could view images of a different user. I tried using the preferLinkOverStore option but it does nothing.

**Comment by pcholuj** [comment]
Ok. If i understand it good, Picker cant download image to crop it? 
If so, you can disable transformations in picker options, and after storeFile you can use picker.crop with policy generated with uploaded file (you an pass handle during policy generation).
