### ISSUE TITLE
`client.upload` doesn't set methods on the `token` object

### ISSUE THREAD

**Issue by muratakbal** [filestack/filestack-js#19]
Hi,

I've been trying to use `.upload` method on the client. It works fine for uploading but you cannot `cancel` or `pause` the upload by calling the methods on the token object. It says those methods are `undefined`. I followed the docs in https://github.com/filestack/filestack-js#clientuploadfile-uploadoptions-storeoptions-token--promise, but it didn't work. 

here is the video ss: http://recordit.co/DmiItLe9iP
here is the `codepen` to test it: https://codepen.io/muratakbal/pen/xdmdjv

let me know if you need more info or sth I'm missing in my code.

**Comment by velveteer** [comment]
@muratakbal Sorry about that. It looks like I forgot to add the token parameter to the API wrapper. I just released 0.6.1 to address this issue. Let me know if that solves the issue for you.

**Comment by muratakbal** [comment]
that worked. thanks 👍
