### ISSUE TITLE
is this is compatable with angular 5

### ISSUE THREAD

**Issue by santhoshraju621** [filestack/filestack-js#190]
Hi is this will work with angular 5. or is it possible to integrate it with anular framework.

**Comment by pcholuj** [comment]
Hi 
For now, you should be able to write your own component with picker integration. We are planning to update filestack-angular to support the newest version.

**Comment by AndrzejSala** [comment]
@santhoshraju621 
Here https://github.com/filestack/filestack-angular#usage
you can find the newest filestack angular module which also include a picker component.
