### ISSUE TITLE
Invalid character in IE11

### ISSUE THREAD

**Issue by emeryowa** [filestack/filestack-js#193]
It seems the filestack.js is not correctly transpiled.

In IE11 it gives an `Invalid Character` error on the backtick on the code e=`${e}`
https://static.filestackapi.com/filestack-js/1.x.x/filestack.min.js

This happens also on one of your tutorial pages. https://www.filestack.com/docs/tutorials/picker-form/

**Comment by zacharyhamm** [comment]
It looks like ie11 testing was dropped here: https://github.com/filestack/filestack-js/commit/521ad62a3c910f8a3a6e11c07fe6266972bb5803#diff-a2a3b7b0c9c3b4b93b4aebf4e3ec3cfb

Is filestack dropping support for ie11?

**Comment by zacharyhamm** [comment]
On further investigation the issue is this one: https://github.com/filestack/filestack-js/issues/139

**Comment by zacharyhamm** [comment]
PR here to downgrade atob again https://github.com/filestack/filestack-js/pull/196

**Comment by nickbaum** [comment]
I can confirm that we're seeing this issue as well, looking forward to a fix!

**Comment by pcholuj** [comment]
Thanks for PR :) Fixed with newest release 1.13.2
