### ISSUE TITLE
Uglification failed

### ISSUE THREAD

**Issue by mixalistzikas** [filestack/filestack-js#194]
filestack-1.10.0.min.js (EVERYTHING IS OK)
filestack-1.12.1.min.js (ERROR)

[Npm install and grunt] >> Uglifying source /general/js/filestack/filestack-1.12.1.min.js failed.
[Npm install and grunt] Warning: Uglification failed.
[Npm install and grunt] SyntaxError: Unexpected character '`'. 
[Npm install and grunt] Line 18 in /general/js/filestack/filestack-1.12.1.min.js

I'm using grunt.loadNpmTasks('grunt-contrib-uglify');

**Comment by pcholuj** [comment]
Hi. For now, can you use uglify with support for es6? This is known "bug" and we will resolve it in upcoming releases.

**Comment by pcholuj** [comment]
Fixed in 1.13.2
