### ISSUE TITLE
Failed to minify

### ISSUE THREAD

**Issue by thinknoise** [filestack/filestack-js#197]
when trying to build react project with filestack-react or without filestack-react, I get this error:

```
Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file: 
 	./node_modules/filestack-js/build/browser/index.esm.js:14048 
Read more here: http://bit.ly/2tRViJ9
```
tried installing the react-scripts as suggested in the bit.ly link

any help would be greatly appreciated

**Comment by pcholuj** [comment]
This should be fixed in new release 1.13.2
