### ISSUE TITLE
older Safari browsers issue while loading script from url

### ISSUE THREAD

**Issue by checho221** [filestack/filestack-js#199]
i am loading script from https://static.filestackapi.com/filestack-js/1.x.x/filestack.min.js, working well for modern browsers but not for Safari old versions
![image](https://user-images.githubusercontent.com/10603888/52376643-9d750700-2a30-11e9-890f-56e087c99cd1.png)

It says certificate is expired

![image](https://user-images.githubusercontent.com/10603888/52376763-efb62800-2a30-11e9-8abe-9f4a63b03205.png)

"can not stablish a secure conection with server 'static.filestackapi.com' "

**Comment by pcholuj** [comment]
Can you provide browser version?

**Comment by maryfs** [comment]
Hi @checho221 please contact support if its still an issue.
