### ISSUE TITLE
Force crop

### ISSUE THREAD

**Issue by zimme** [filestack/filestack-js#2]
I'm missing the force crop functionality, would be awesome to have that again. Really useful for uploading profile pictures etc.

**Comment by velveteer** [comment]
Hey @zimme, thanks for the feedback. We will definitely add this functionality to our roadmap, and I'll do my best to let you know when that lands.

**Comment by zimme** [comment]
Fair enough, keep up the good work!

**Comment by JamieREvans** [comment]
Is there a timeline for this functionality? We can't update to V3 without it.

**Comment by velveteer** [comment]
@JamieREvans We are working on getting that feature where we want it. The new 0.5.0 release includes a better flow for single images, so selected images are immediately loaded into the transformations UI (unless `disableTransformer` is true). Of course this does not address forcing transforms for multiple images, and certain options like setting exact crop dimensions are still missing. We apologize for the lack of v2 parity right now, but we're getting there. Hopefully v2 can still meet your needs in the meantime.

**Comment by velveteer** [comment]
As of 0.8.0 `transformations.crop.force` will enable the force crop flow.
