### ISSUE TITLE
transform throws "Invalid filestack source provided" in Safari when using handle as url

### ISSUE THREAD

**Issue by rrivem** [filestack/filestack-js#203]
I have this code:
```js
const client = init(apiKey);
const handle = // filestack handle, 20 alphanumeric characters
const resizeUrl = client.transform(handle, { resize: { height: 200 } });
```

The call to transform throws the error "Invalid filestack source provided" when running in Safari 12.0.3, works fine in Chrome and Firefox. When looking at the code, I found that the [regex](https://github.com/filestack/filestack-js/blob/7d0c8023dcbc2f35ec7ca13abd9a10c10dbb9c21/src/lib/filelink.ts#L423) that the handle is matched against is failing, throwing the error.

If I change the regex from `new RegExp('^([_\\w\\-]+){20}$')` to `new RegExp('^([_\\w\\-]){20}$')`, the handle matches the pattern, and the error is not thrown.

The workaround is to use FileStack's url (storage alias) or storage url (S3 for instance), cause the handle regex check is not performed for those.

**Comment by pcholuj** [comment]
Hi, this one should be fixed. Can you confirm it?

**Comment by rrivem** [comment]
Works fine in 1.14.2!
