### ISSUE TITLE
Passing container node causes JSON.stringify error

### ISSUE THREAD

**Issue by darkowic** [filestack/filestack-js#206]
I'm using filestack together with react. I'm trying to open the picker in the inline mode using the following code:
```jsx
    this.picker = this.client.picker({
      // container: '#filestackContainer',
      container: this.container.current,
      displayMode: 'inline'
    });
```
`this.container` is reference to the element I want to inject the picker. Unfortuanetly, passing node couses error:
```js
logger.es2015.js:100 Uncaught (in promise) TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at logger.es2015.js:100
    at Array.map (<anonymous>)
    at e (logger.es2015.js:98)
    at new t (index.js:226)
    at PickerLoader.eval (index.esm.js?c7bf:18650)
    at step (index.esm.js?c7bf:265)
    at Object.eval [as next] (index.esm.js?c7bf:195)
    at fulfilled (index.esm.js?c7bf:148)
```
The error is gone when passing `container` option as a string id of the container. There is no source code for your API package so I can not debug it...

Btw the package is huge! 57 Kb gzipped...
https://bundlephobia.com/result?p=filestack-js@1.14.3

**Comment by pcholuj** [comment]
Hi it should work in newer releases like https://jsfiddle.net/p85uv63y/
