### ISSUE TITLE
Incorrect words order of german translation ''You need to authenticate with <cloud service>"

### ISSUE THREAD

**Issue by darkowic** [filestack/filestack-js#207]
![socialmedia](https://user-images.githubusercontent.com/11510581/54366055-41755200-4670-11e9-9184-9210ddf87208.jpg)

> Where "here Social Media Service" stands, the selected Social Media Service should stand. If the "anmelden" is placed before the Social Media Service, it is a wrong German.

Hello!

German translation order is incorrect for phrase `You need to authenticate with `. I see there is no option to change the order for now:
https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#customtext
https://filestack.github.io/filestack-js/interfaces/pickercustomtext.html#you_need_to_authenticate_with_
as there are not runtime values for this text.

**Comment by AndrzejSala** [comment]
@darkowic 
In the newest version we fix this translation.

We also add a new custom text like 'You need to authenticate with {providerName}.' in which you can change order of {providerName} in translated sentence.
