### ISSUE TITLE
Drag And drop images does not work

### ISSUE THREAD

**Issue by ericvillemure** [filestack/filestack-js#21]
The problem is that once you drop the file Chrome opens the file instead of uploading it inside the filestack window (like it would normally do when no drag and drop is enabled)

I haven't found the exact cause of the issue but I was able to reproduce the problem here:

https://www.filestack.com/products/file-uploader

NOTE that it works in the Upload File button here:

https://www.filestack.com/

Let me know if you need more info

**Comment by sptessier** [comment]
+1 having the same issue

**Comment by velveteer** [comment]
@ericvillemure @sptessier If possible can you update to 0.7.0 and let us know if this is resolved? I am unable to reproduce the issue in Chrome on the link provided. If it's still happening we would be grateful for any detailed steps to reproduce.

**Comment by sptessier** [comment]
@velveteer Sorry for the late reply but I upgraded to latest npm release filestack-js (0.7.1) and I'm unable to reproduce the issue.

Thanks
