### ISSUE TITLE
How to setSecurity to update an existing client?

### ISSUE THREAD

**Issue by wuservices** [filestack/filestack-js#211]
I'm upgrading from a pre-1.x version of filestack-js. I was previously using setSecurity to update security policy and token periodically from a server on a shared filestack instance. In the current version of the SDK, is there a new way to achieve this or is the only way to create a new client instance every time I need to update credentials? That would be less ideal since my app is using a singleton instance right now.

**Comment by pcholuj** [comment]
Hi, currently we can overwrite variable in client session ie
client.session.policy
client.session.signature 

We are going to add the method u mentioned in a new major release soon.

**Comment by pcholuj** [comment]
Hi. New filestack js have method setSecurity for this:)
https://github.com/filestack/filestack-js/blob/master/src/lib/client.ts#L116
