### ISSUE TITLE
Parameters are invalid

### ISSUE THREAD

**Issue by meyer59** [filestack/filestack-js#215]
Hi
I keep receiving this error (in the console) when i am trying to upload a file through the picker
`POST https://upload-eu-west-1.filestackapi.com/multipart/upload 400 (Bad Request)`
`{"error":"Parameters are invalid","c":{"ujid":"59183255-e3de-40e9-9104-09da6261cf98","ujid_path":"ul-0"},"i":"","t":1554327314}
`

I will paste below my picker instanciation with the options:
`<script src="http://static.filestackapi.com/filestack-js/2.0.3/filestack.min.js"></script>`
`<script>

const client = filestack.init(************************);

let options = {
  "displayMode": "inline",
  "container": ".picker-content",
  "maxFiles": 4,
  "accept": [
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/bmp",
    "image/gif",
    "application/pdf"
  ],
  "storeTo": {
    "container": "*us***************tv*",
    "path": "local/",
    "region": "eu-west-3"
  },
  "fromSources": [
    "local_file_system"
  ],
  "uploadInBackground": false
};
picker = client.picker(options);
picker.open();
</script>`

I did a support request already but still no answer yet. 
Any help will be greatly appreciated, thanks

**Comment by pcholuj** [comment]
Hi ,currently we are not supporting region eu-west-3. It will be added in next 2 weeks. I will inform you about progress in this issue.

**Comment by meyer59** [comment]
Hi,
So what region are you currently supporting ?

**Comment by maryfs** [comment]
Hi @meyer59 ,

**Comment by maryfs** [comment]
Hi @meyer59 , check new sdk version 3.2.0, support for eu-west-3 was added. Here is full list of supported regions:
`	"us-east-1":      "s3.amazonaws.com",                // US East (N. Virginia)
	"us-east-2":      "s3-us-east-2.amazonaws.com",      // US East (Ohio)
	"us-west-1":      "s3-us-west-1.amazonaws.com",      // US West (N. California)
	"us-west-2":      "s3-us-west-2.amazonaws.com",      // US West (Oregon)
	"ca-central-1":   "s3-ca-central-1.amazonaws.com",   // Canada (Central)
	"ap-south-1":     "s3-ap-south-1.amazonaws.com",     // Asia Pacific (Mumbai)
	"ap-northeast-1": "s3-ap-northeast-1.amazonaws.com", // Asia Pacific (Tokyo)
	"ap-northeast-2": "s3-ap-northeast-2.amazonaws.com", // Asia Pacific (Seoul)
	"ap-northeast-3": "s3-ap-northeast-3.amazonaws.com", // Asia Pacific (Osaka-Local)
	"ap-southeast-1": "s3-ap-southeast-1.amazonaws.com", // Asia Pacific (Singapore)
	"ap-southeast-2": "s3-ap-southeast-2.amazonaws.com", // Asia Pacific (Sydney)
	"eu-central-1":   "s3-eu-central-1.amazonaws.com",   // EU (Frankfurt)
	"eu-west-1":      "s3-eu-west-1.amazonaws.com",      // EU (Ireland)
	"eu-west-2":      "s3-eu-west-2.amazonaws.com",      // EU (London)
	"eu-west-3":      "s3-eu-west-3.amazonaws.com",      // EU (Paris)
	"sa-east-1":      "s3-sa-east-1.amazonaws.com",      // South America (São Paulo)
`
