### ISSUE TITLE
`uploadInBackground` is ignored

### ISSUE THREAD

**Issue by amitport** [filestack/filestack-js#22]
upload starts immediately after file selection when using
```
{
      accept: 'image/*',
      fromSources: 'local_file_system',
      transformations: {
        maxDimensions: [250, 250],
        crop: {aspectRatio: 1, circle: true},
        filters: []
      },
      hideWhenUploading: true,
      uploadInBackground: false // <-- does not seem to work
}
```

**Comment by velveteer** [comment]
@amitport The options you show here indicate the default `maxFiles = 1` setting. This single image flow with transformations enabled is currently designed to upload the image on selection. The reason for this is related to transformations -- the file is processed using the Filestack transformation engine, and as such needs a Filestack handle or a public facing URL. 

I apologize for the confusion -- `uploadInBackground: false` does have a benefit when `maxFiles` is large. But for any images that require transformation they are uploaded regardless of this option.

**Comment by amitport** [comment]
OK, didn't realize you upload the file for those transformations.
Are there plans to move those capabilities to the js client? (at least for small files)

**Comment by velveteer** [comment]
@amitport At the moment there are no plans to do client-side transformations, but if it becomes a highly requested feature then we'll revisit it. And in this case we may look into ways to work around the image upload requirement.
