### ISSUE TITLE
Upload file from url not from Blob

### ISSUE THREAD

**Issue by dryna** [filestack/filestack-js#221]
It there options to upload a file from URL like this:

`curl -X POST -d url="https://d3urzlae3olibs.cloudfront.net/watermark.png" "https://www.filestackapi.com/api/store/S3?key=MY_API_KEY"`

or plan to add it?

**Comment by maryfs** [comment]
Hi, you can use storeUrl:
https://filestack.github.io/filestack-js/classes/client.html#storeurl
