### ISSUE TITLE
Not possible to rename zip file

### ISSUE THREAD

**Issue by frankbracq** [filestack/filestack-js#223]
We need to give specific name to zip file before archive download. How could we do this?

**Comment by AndrzejSala** [comment]
Hi @frankbracq 
A zip transformation doesn't accept any additional params like an archive name, but I think that you could use a 'store' feature in this case.

I am guessing that you are doing something like:
https://cdn.filestackcontent.com/API_KEY/zip/["FIRST_HANDLE","SECOND_HANDLE"]

If you use store option you will be able to stare this zip file with a custom name and our backend will generate an another handle for it:
http://cdn.filestackcontent.com/API_KEY/zip/store=filename:theAwesomeArchive.zip/["FIRST_HANDLE","SECOND_HANDLE"]

and that req will produce json with handle for "theAwesomeArchive.zip" used in this example :
{
	"filename": "theAwesomeArchive.zip",
	"handle": "THE_AWESOME_ARCHIVE_ZIP_HANDLE",
	"size": 3620149,
	"type": "application/x-zip-compressed",
	"url": "https://cdn.filestackcontent.com/THE_AWESOME_ARCHIVE_ZIP_HANDLE"
}

**Comment by frankbracq** [comment]
Will give it a try. Thanks

**Comment by Max-Zviagintsev** [comment]
Hi, @AndrzejSala !
I'm using these links you mention as an href attribute of the <a> tag and when I add /store... it redirects from the current page to the JSON output page.
Is it possible to prevent it from redirecting and just send the data to my React app?
Thank you!

**Comment by AndrzejSala** [comment]
@Max-Zviagintsev 
Hi,
No, it's not possible for now to get a direct redirect by using store task. So you need to generate it by your backend and preferably only once, because it generate a new handle every time. 

It's just a workaround,  and we need to find a more appropriate way to do this in the future.

**Comment by Max-Zviagintsev** [comment]
OK, thanks for the explanation, Andrzej!
