### ISSUE TITLE
Upload a large file by upload function throws error about buffer limit

### ISSUE THREAD

**Issue by AngelRodRo** [filestack/filestack-js#224]
When I try to upload a large file (+5GB) with the `client.upload` function in nodejs it throws an error:

`RangeError: File size is greater than possible Buffer: 0x7fffffff bytes`

What can I do for handle this when I work with this type of files? I was using this SDK because I read this allow to upload a large files through chunks but if I can't use it, what else can I use for upload this type of files?

**Comment by maryfs** [comment]
Hi,
I cannot reproduce your issue, please use latest flestack-js - 2.x.x , if problem still occurs 
we need more details about your account etc. Please contact our support team directly via email support@filestack.com.

**Comment by kentonlin** [comment]
I'm currently running into this same issue when trying to upload a file that is 2.4 gb. Are there UploadOptions that will enable me to solve this issue?
