### ISSUE TITLE
Japanese translation for no search results

### ISSUE THREAD

**Issue by chuckcarpenter** [filestack/filestack-js#227]
When using Japanese translation, english result still comes up there are no search results. 

![](https://user-images.githubusercontent.com/24593072/57395591-51e00f80-717d-11e9-85a9-0350c3e64ee6.png)

This text cannot be override in `customText` object. 

English text = “No result can be found for “searched word(s)”.
Insert Japanese translation -> "searched query"に該当するものはありません

**Comment by pcholuj** [comment]
Hi. This message should be now available to translate: Key for custom text is 
'No search results found for "{search}"'

**Comment by chuckcarpenter** [comment]
@pcholuj is this tied to a code release? Or can I use it today w/o updating my dependencies?
