### ISSUE TITLE
Can't crop files in dropPane mode

### ISSUE THREAD

**Issue by wfifer** [filestack/filestack-js#228]
It's entirely possible that I'm conceiving of this incorrectly—this particular case isn't documented anywhere to my knowledge. I've got `displayMode: dropPane` working fine in React, but the `dropPane: { cropFiles }` option only seems to do one thing: disable the input when a file is selected/dropped. This, to me, indicates that _something_ is supposed to be appearing (i.e. the usual crop overlay), but I can't see any other changes in the DOM. 

See the cropFiles option added here in your "Multiple Drop Panes" fiddle: https://jsfiddle.net/4ksnqh18/1/

**Comment by pcholuj** [comment]
Hi. We found a bug in our code. It will be fixed in next release

**Comment by pcholuj** [comment]
Fixed in 3.0.0 release :)
