### ISSUE TITLE
Missing and wrong translation keys

### ISSUE THREAD

**Issue by killiansc** [filestack/filestack-js#229]
Hey,

I am using filestack-react (version 2.0.6), which itself is using filestack-js (version 2.1.0). I am using the `customText` property to send translations, but some of them are missing and some of them are wrong. 

Here is a list of missing translation keys:

* **To disconnect from Google Drive click 'Sign out' button in the menu** - this translation doesn't work, and "Google Drive" should certainly be "{provider}"
* **Click here or hit ESC to close picker** - this is the title of the cross to close the modal
* **Upload More**
* **Sign in with Google**

Here is a list of wrong translation keys:

* **Select Files from** - this one misses "{provider}" in it, as the provider might come in the middle of the sentence in some languages, and not always at the end
* **You need to authenticate with** - same story as above, and this key has a space at the end, which I find strange

There might be more, but I am only using the upload feature, so these are the ones that I know of.

--

On another hand, using the `lang` parameter instead doesn't translate:

* **Sign in with Google**
* **Click here or hit ESC to close picker**

Thanks,
Killian

**Comment by AndrzejSala** [comment]
Hey kiliansc,
answering your questions:
“Sign in with Google”  and “Click here or hit ESC to close picker” should be definitely  added to customText option and  you should be able to translate them with lang option. I will fix it.

When it comes to “Upload More” it looks like you are using wrong key, it should be “Upload more”.

For now we don’t support possibility to mix strings with some variables (like for example with {provider}), customText is a simple replace, but for texts from cloud provider auth screen like:
- “You need to authenticate with ” (yes, space should be removed)
- “We only extract images and never modify or delete them.”
- “A new page will open to connect your account.”
- “To disconnect from“
- “click 'Sign out' button in the menu.”
except customText option you can use [customAuthText](https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#customauthtext) which allow you to write your own text for them (for example without tricky provider name).

**Comment by killiansc** [comment]
Thanks for your answer @AndrzejSala,

You actually support the possibility to mix strings with some variables, for example with **File {displayName} is not an accepted file type. The accepted file types are {types}** and **File {displayName} is too big. The accepted file size is less than {roundFileSize}**, so I guessed you could do the same for the providers.

Indeed, **Upload more** is with a lowercased "m". Maybe you could update the [documentation](https://filestack.github.io/filestack-js/interfaces/pickercustomtext.html), as this key is not there?

**Comment by AndrzejSala** [comment]
@killiansc 
With the last release we fix some translations and add new keys for customText option like:
'Connect {providerName}'
'Select Files from {providerName}'
'You need to authenticate with {providerName}.'
'To disconnect from {providerName} click "Sign out" button in the menu.'
'Sign in with Google'
'Go back'
'This folder is empty.'
'Click here or hit ESC to close picker'
