### ISSUE TITLE
Upload twice the same file gives same Upload id

### ISSUE THREAD

**Issue by meyer59** [filestack/filestack-js#230]
Hi
If we upload twice the same image through the image google search tool in the picker we got the same upload id in the json response.
Step to reproduce:
Open the picker, search for an image in the image search tab.
Upload the image, close the picker (Do not refresh the page).
Re-open the picker, open the image search tab, upload the same image.
You should have the same upload id in the response.
Is this a normal behavior ? I thought that the upload id should be unique
Cordially

**Comment by pcholuj** [comment]
Hi
UploadId should be unique ure right. I reproduced this bug and we will fix it in the upcoming release

**Comment by meyer59** [comment]
FYI the image isn't uploaded again but, the js callback is still fired

**Comment by pcholuj** [comment]
Hi :) thanks for feedback. Version 3.0.0 should work as expected.
