### ISSUE TITLE
Unhandled promise rejection TypeError: Object doesn't support property or method 'parseInt'

### ISSUE THREAD

**Issue by killiansc** [filestack/filestack-js#231]
Hey,

In Internet Explorer 11, clicking on a file in the file picker (after logging in with Google Drive) throws an error in the console: `Unhandled promise rejection TypeError: Object doesn't support property or method 'parseInt'`. The file is of an accepted mime type and should just be selected as a file to upload.

It would be very nice to have a list of supported browser by the way - I wasn't able to find it so far.

I am using filestack-react (version 2.0.6), which itself is using filestack-js (version 2.1.0).

Thanks,
Killian

**Comment by AndrzejSala** [comment]
@killiansc 
I will check it.

You will find the list of supported browser at the top of readme and IE 11 is also on it.

**Comment by killiansc** [comment]
@AndrzejSala oh yes, I missed it, thanks! :-)

**Comment by maryfs** [comment]
@killiansc could you post full configuration?

**Comment by pcholuj** [comment]
Hi can you confirm that new 3.0.0 release fixed that problem ?

**Comment by killiansc** [comment]
@pcholuj yes, but only as soon as the React component uses 3.0.0

**Comment by pcholuj** [comment]
:) Thanks for the confirmation. We will release new version of filestack-react soon:)

**Comment by pcholuj** [comment]
Hi. Fs-react is now using new version 3.x.x has been released:)
