### ISSUE TITLE
Uploading from Facebook/GoogleDrive/etc doesn't work

### ISSUE THREAD

**Issue by thekip** [filestack/filestack-js#232]
Uploading and crop files from local machine work perfectly.
Connecting and browsing cloud sources (facebook, googledrive, etc) works, but if I choose an image the cropper shows the following error:

> This image cannot be edited

![image](https://user-images.githubusercontent.com/1586852/58235378-fd25c280-7d40-11e9-8bd6-ba655f5b468a.png)

The src tag for the image in the modal that I was attempting to crop was undefined.

Network requests:

![image](https://user-images.githubusercontent.com/1586852/58235553-555cc480-7d41-11e9-9f4a-737cdb35fe22.png)

The store request respond with 

> Error requesting cloud, error reading response

I found similar issue https://github.com/filestack/filestack-js/issues/143 but we use Amazon S3 as a storage

**Comment by pcholuj** [comment]
Hi can u provide picker options on some example ie on JS Fiddle?

**Comment by thekip** [comment]
```typescript
  public async ngOnInit() {
    const policy = await this.requestPolicy();
    const filestack = await import (/*webpackChunkName: 'filestack-client'*/'filestack-js');

    const client = filestack.init(TS.filestack.key, {
      security: policy,
    });

    this.picker = client.picker({
      accept: 'image/*',
      maxSize: 5 * 1024 * 1024,
      maxFiles: 1,
      lang: LANGUAGE,
      customText: pickerCustomText as PickerCustomText,
      storeTo: {
        access: 'public',
        location: 's3',
        path: policy.allow_path,
      },
      onFileUploadFailed: () => {
        this.flashMessages.show({title: t('Can\'t upload image'), text: t('Please try again later')}, 'error');
      },
      onUploadDone: (files) => {
        if (files.filesUploaded.length) {
          this.loaded.emit([{
            id: files.filesUploaded[0].handle,
          }]);

          files.filesUploaded.forEach((file) => {
            this.saveImage(file.handle);
          });
        }
      },
    });
  }
```

Provide Js Fiddle is impossible because we use security features and signature/policy generated by backend for every upload.

**Comment by maryfs** [comment]
Hi @thekip , please contact our support, we need your apikey.
