### ISSUE TITLE
Missing callbacks and transformations in dropPane mode crop tool

### ISSUE THREAD

**Issue by wfifer** [filestack/filestack-js#235]
Thanks for fixing #228—dropPane mode is nearly usable now. See fiddle (insert API key): 

https://jsfiddle.net/8eynobLr/4/

Specifically when using `dropPane: { cropFiles: true }`, `onSuccess` does not fire (oddly, `onProgress` does). If I leave `cropFiles` off, `onSuccess` fires just fine. I've tried all the main callbacks also, but as expected from the documentation, none of them fire. 

I'm also seeing that `transformations` don't get passed to the crop tool. We use a number of forced aspect ratios, so this is also quite important to have working. 

Cheers.

**Comment by pcholuj** [comment]
Hi. Thanks for reporting this issue. We will release fix today

**Comment by pcholuj** [comment]
Hi. dropPane should now work correctly in 3.2.0
