### ISSUE TITLE
Incorrect import path in Typescript Sources

### ISSUE THREAD

**Issue by thekip** [filestack/filestack-js#237]
Guys, WTF? 

https://github.com/filestack/filestack-js/blob/master/src/lib/api/upload/types.ts#L18

![image](https://user-images.githubusercontent.com/1586852/58792651-e6ab2100-85f4-11e9-9a8a-e8f54d3b5c58.png)

![image](https://user-images.githubusercontent.com/1586852/58792685-f165b600-85f4-11e9-8e7c-2c0620b4d53d.png)

**Comment by thekip** [comment]
PS, all paths should start from "./" otherwise they are treated as packages in node_modules, or should have special handling via module bundler/typescript

**Comment by pcholuj** [comment]
Hi. Its fixed in 3.2.0
