### ISSUE TITLE
in upload method, storeOptions.path seems to not send the correct parameter name

### ISSUE THREAD

**Issue by cyrilepinat** [filestack/filestack-js#24]
I would like to store my file in a custom folder.
When I call upload method (https://github.com/filestack/filestack-js#clientuploadfile-uploadoptions-storeoptions-token--promise) like this: 
```
upload(myFile,
        {
          onProgress: (progress) => {
               ....
          },
        },
        {
          path: 'toto/'
        }
      )
```
the request content has this body parameter:
```
Content-Disposition: form-data; name="store_path"

toto/
```

But it seems to not be taken in account (my file is still stored in root folder) and if I check filestack  javascript API (https://www.filestack.com/docs/javascript-api/upload-v3) the param name is `path` instead of `store_path` 

Am I missing something or is it a naming issue to fix ?
Thanks for your help

**Comment by velveteer** [comment]
The form-data parameter to the service is `store_path`, but in the JS client it is simply `path`. Are you still having this issue? I am unable to reproduce the problem on the latest version (0.7.0) using my own S3 bucket.
