### ISSUE TITLE
Callback on individual transformation change in picker

### ISSUE THREAD

**Issue by natwales** [filestack/filestack-js#244]
I suspect this is more of a feature request than anything but is there any way by which to listen to transformation change events, or even a single callback when image transformations have been accepted and the image is ready to upload?

**Comment by pcholuj** [comment]
Hi. For now, we don't have callback like this, but I will mark it as a feature request so we can probably add it in one of the next releases.

**Comment by pcholuj** [comment]
Hi. We added a callback for image transformations in the newest version.
