### ISSUE TITLE
Picker on iOS doesn't work correctly with PDFs

### ISSUE THREAD

**Issue by gligoran** [filestack/filestack-js#246]
On iOS, when setting the `accept` parameter in picker options to only accept `application/pdf`, it doesn't restrict choosing other file types in the iOS file selector.

![image](https://user-images.githubusercontent.com/444829/59446232-63ae7580-8e01-11e9-884c-f5f271a43dd9.png)

```js
const client = filestack.init(YOUR_API_KEY);

const options = {
  accept: [
    'application/pdf'
  ],
  fromSources: ['local_file_system'],
};

client.picker(options).open();
```

![image](https://user-images.githubusercontent.com/444829/59446293-82147100-8e01-11e9-81c2-cddde007d101.png)

On the other hand, if `image/png` is also present in the `accept` option, it disables PDF documents:

```js
const client = filestack.init(YOUR_API_KEY);

const options = {
  accept: [
    'image/png',
    'application/pdf'
  ],
  fromSources: ['local_file_system'],
};

client.picker(options).open();
```

![image](https://user-images.githubusercontent.com/444829/59446400-bd16a480-8e01-11e9-8aac-51b4681feaeb.png)

It works the same for `.pdf`.

Here's a plunker to test it out: https://next.plnkr.co/edit/ZUpRZQG1qVEhzIaz

**Comment by pcholuj** [comment]
Hi its a ios problem https://github.com/filestack/filestack-js/issues/246 ,but in picker we have checking file type as well so user shouldn't be able to upload incorrect file

**Comment by vidrepar** [comment]
It works when mime types are excluded from the _accept array_. Just use file extensions (.pdf, .jpg...) instead of application/pdf or image/jpeg.

@pcholuj Can we add this to the docs, please? Or is this info already somewhere?
