### ISSUE TITLE
Video Recording appears to be broken.

### ISSUE THREAD

**Issue by denodster** [filestack/filestack-js#248]
![60022605-29936e00-9662-11e9-8de6-b6c1502ca2cd](https://user-images.githubusercontent.com/1984743/60025921-a590b480-9668-11e9-94f6-80cd073ad456.png)

**Comment by denodster** [comment]
it just hangs here. no errors in console. here's my configuration:

fromSources: [
'video',
'webcam'
],
videoResolution: '1280x720',
accept: [
'video/*'
],
storeTo: {
location: 's3'
}

**Comment by pcholuj** [comment]
Hi. 
Thanks for reporting the issue, We fixed it in 3.3.4.

**Comment by gearheart** [comment]
It seems to still be broken in 3.24.1, but works in 3.22.1. Shows exactly the same image as posted above.

I just specify a minimal config:
```
  fromSources: ["video", "webcam"]
```

Webcam works fine, but video just shows an empty modal.

https://codesandbox.io/s/late-haze-vj9m2?file=/src/index.js
