### ISSUE TITLE
cleanupImageExif is not removing exifs when upload from google drive

### ISSUE THREAD

**Issue by darkowic** [filestack/filestack-js#251]
Setting the [`cleanupImageExif`](https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#cleanupimageexif) is not removing the image exifs when uploading an image from google drive.

Try it here: https://jsfiddle.net/Darkowic/gat3zs5q/

Steps to reproduce:
1. Download photo with exifs from google drive
2. Download the photo and check the photo exifs - they are still there ([Linux tool](http://manpages.ubuntu.com/manpages/bionic/man1/exif.1.html))

**Comment by pcholuj** [comment]
Hi. 
For now, cleanupImageExif is only supported in local uploads. I will mark it as a feature request.

**Comment by darkowic** [comment]
@pcholuj one more question btw. Let's say there is a rotated photo. Will `cleanupImageExif ` option first rotate the photo to the correct position and then remove the exifs?

**Comment by pcholuj** [comment]
This options is only for cleaning exif data, you can set `keepOrientation` to keep exif orientation only. If you want to rotate image to exif you can use rotate transformation with option deg: exif
https://www.filestack.com/docs/api/processing/#rotate

**Comment by darkowic** [comment]
Thank you so much @pcholuj ! It solved my problem with rotations.

But I have one more question - to apply image processing I have to modify the photo URL returned by picker after upload. Is it possible to configure the picker to always apply specific processing options to the uploaded image?

Now I do it this way... The `url` is from picker file
```
  applyImageProcessing(url) {
    const splitUrl = url.split('/');
    splitUrl.splice(splitUrl.length - 1, 0, 'rotate=deg:exif/resize=height:800,width:800,fit:max/compress');
    return splitUrl.join('/');
  }
```

**Comment by pcholuj** [comment]
Hi.
Unfortunately no, for that image processing you can use our workflows https://www.filestack.com/docs/concepts/workflows/
But you will get new filelink in webhook after workflow will finish. Those are only two options for now,

**Comment by darkowic** [comment]
Btw you close the issue (yeah, you helped solve my problem) but the feature to remove exifs when uploading from other sources than the user device still may be useful for someone ;)
