### ISSUE TITLE
'const' keyword in a build file causing incompatibility with iOS Safari 9.3

### ISSUE THREAD

**Issue by davidlima88** [filestack/filestack-js#252]
The file build > browser > filestack.esm.js contains the keyword 'const'.

Safari and Chrome for iOS 9.3 have only partial support for ES6, however, this version is still widely used (iPad 2nd gen and iPad 3rd gen models) and they cannot be upgraded past iOS 9.3.5

**Comment by pcholuj** [comment]
Hi. 
Can you use filestack.min.js file, it is compiled to support es5

**Comment by davidlima88** [comment]
Hi,
Thanks for the quick reply.
I am not sure about how to replace the current ES Module import with a CommonJS require of the filestack.min.js file.
Is there a previous version of filestask-js that I could switch to with ES5 support?

**Comment by davidlima88** [comment]
We were able to link filestack-js to filestack.min.js in the webpack.config.js file. This way, the imports to filestack-js inside filestack-react use the ES5 compatible version as well:

`
resolve: {
    alias: {
      'filestack-js': path.resolve(__dirname, 'node_modules/filestack-js/build/browser/filestack.min.js')
    },
    modules: ...
`
