### ISSUE TITLE
customSource's file size metadata type isn't consistent - PickerFileMetadata inconsistent

### ISSUE THREAD

**Issue by ease** [filestack/filestack-js#257]
If we are using [**customSource**](https://www.filestack.com/docs/concepts/pickers/#custom-s3-source) and trying to get the file metadata on `onFileSelected` callback (as it's explained in [here](https://github.com/filestack/filestack-js/blob/master/src/lib/picker.ts#L568) and set [here](https://github.com/filestack/filestack-js/blob/master/src/lib/picker.ts#L141)), we see that the file size is actually returned as a **string** `size: "7.3 KB"`, which really makes a problem and isn't comparable in any way (i.e. if we want to validate if the file size is under xy kb), we can't:
`if file.size < 5000`
Here's the full file metadata:
```
filename: "XJHrblXBSpqtjnuqTet1_small-image.jpeg"
handle: undefined
mimetype: "image/jpeg"
originalPath: "/XJHrblXBSpqtjnuqTet1_small-image.jpeg"
size: "7.3 KB"
source: "customsource"
uploadId: "34fc158e6e71afe15147bf45584392a93"
url: undefined
```

On the other side, if we use **upload from our PC** (`local_file_system`), it will normally return the following metadata:
```
filename: "small-image.jpeg"
handle: undefined
mimetype: "image/jpeg"
originalFile:
name: "small-image.jpeg"
size: 7515
type: "image/jpeg"
__proto__: Object
originalPath: "small-image.jpeg"
size: 7515
source: "local_file_system"
uploadId: "317b538996572321ea3649b1947e37447"
url: undefined
```
Here you can see that the file.size is provided as a _number_ - 7515 in kb

Could someone please help, since I want to disallow user to choose image larger than xy MB in some cases.

Filestack Version: 1.6.1
Amazon S3 is used as a Custom source.

**Comment by pcholuj** [comment]
Hi. 
Thanks for reporting this bug. As a workaround for now you can check if size is a string and ie use https://www.npmjs.com/package/bytes to convert it to bytes.
