### ISSUE TITLE
How to filter out formats not supported for transformation

### ISSUE THREAD

**Issue by marcohamersma** [filestack/filestack-js#259]
Hey there,
We use the Filestack Picker to allow our users to upload images, after which we transform them (process.filestackapi.com, etc). For the picker parameters we set `accept` to `['image/*']`, but we realised that not every type of image is accepted by filestack's image pipeline. 

For example, a user recently wrote in that they were trying to upload a `.jp2` image, which caused filestack to return an error when requesting the transformed image:

```
conv20 provider error: image/jp2 conversions are not supported (idx 0)
```

It would be great to have a way of automatically rejecting images supported by filestack's image processing without having to (as a user of your SDK) manually whitelist formats that you know are supported. A way of blacklisting certain formats that might otherwise be allowed by `image/*` would be good as an alternative. 

What would you think is the best way of dealing with this?

**Comment by pcholuj** [comment]
Hi @marcohamersma, you can add to accept param all supported formats listed in this transformation matrix https://cdn.filestackcontent.com/UPqbkTIETnGaQJa1nqnG
So:
```
["image/jpeg", "image/jpeg", "image/png", "image/webp", "image/xvg+xml", "image/heic", "image/heif", "image/bmp", "image/tiff", "image/photoshop", "image/psd", "image/x-psd", "image/vnd.adobe.photoshop"]
```

**Comment by pcholuj** [comment]
@marcohamersma if something is not clear, just reopen the issue. Thanks :)

**Comment by septianopraditya** [comment]
I have same issue here. Like this pic 
![image](https://user-images.githubusercontent.com/33999083/79735347-57991b80-8322-11ea-9102-35dce41ab774.png)
