### ISSUE TITLE
Google Photos/Instagram selection not working at first

### ISSUE THREAD

**Issue by seishin4real** [filestack/filestack-js#260]
Hi,
we're using the UMD module from http://static.filestackapi.com/filestack-js/1.x.x/filestack.min.js

Tester had the same issues with Instgram, I could not repro

Steps to reproduce:
- open the upload dialog
- select Google Photos (link account if needed)
- list of directories appear, navigate to one
- list of images appear, select any number
note that the selection is reflected in the indicators but not on the item (see first part of the scr).
- after clicking on ex. My Device and back to Google Photos the selection works correctly (second part of the scr)

![image](https://user-images.githubusercontent.com/866482/61375787-0db96b80-a8a0-11e9-8a96-b543bd5712fc.png)

**Comment by maryfs** [comment]
Hi @seishin4real ,
i was testing it on newest version (3.4.2) and cant reproduce it, could you try to on newest version?
Thanks.

**Comment by seishin4real** [comment]
Hi @maryfs,
no, it appears to be fixed, thanks
