### ISSUE TITLE
Picker cropped data in response is inconsistent

### ISSUE THREAD

**Issue by timbuncee** [filestack/filestack-js#261]
Cropped property in PickerFileMetadata doesn't always appear. On uploadDone, I console logged the response and found that cropped data is only showing when all 4 control point is used.

1. Cropped using left
![dc08cc5684af2814d6dff0bd9ede893c](https://user-images.githubusercontent.com/38078854/61411304-14ea7480-a8b4-11e9-8fe2-e2118ad56ead.png)
<img width="1280" alt="68a3b6a7aeae79b12d7b557f8de2212e" src="https://user-images.githubusercontent.com/38078854/61411314-1ae05580-a8b4-11e9-9d0d-7f633da56602.png">

https://cdn.filestackcontent.com/k6mLyd5TBGWq82xbjJHQ

Cropped property is missing

2. Cropped using bottom right controller
![6f9a43791c62cc73fca4eb1f1b4a24ae](https://user-images.githubusercontent.com/38078854/61411587-ae198b00-a8b4-11e9-9533-d2fe160144e8.png)
<img width="1261" alt="792eb45f2be5548a5df63e22a0d1a4b8" src="https://user-images.githubusercontent.com/38078854/61411630-c9849600-a8b4-11e9-85ff-09ab10d02ac6.png">

https://cdn.filestackcontent.com/v4aTq1uHTgiHCZGWCNeF

Cropped property is missing

3. Cropped using all controller
![31ac4ea0510db5015b1c957fd8c00edd](https://user-images.githubusercontent.com/38078854/61411858-5c253500-a8b5-11e9-8fb9-d42c1f17b6aa.png)
<img width="1280" alt="343ee3b9741c555c1ac4873f0c0e4ae9" src="https://user-images.githubusercontent.com/38078854/61411868-5f202580-a8b5-11e9-8b4c-3502554a4836.png">

https://cdn.filestackcontent.com/KHXIJOFmRWWvVEjbBIPu

Cropped property is now showing

**Comment by maryfs** [comment]
Hi @timbuncee ,
thanks for reporting this. Currently we are working on new cropper, we will make sure it will work on new version.

**Comment by pcholuj** [comment]
Hi this should be fixed v3.5.0
