### ISSUE TITLE
Unable to convert TIFF image to PNG

### ISSUE THREAD

**Issue by gsdefender** [filestack/filestack-js#265]
Hi, it seems that this Photoshop-produced file cannot be properly converted to PNG using the API, as the image is not properly recognized.

https://bayfiles.com/K5c0Ne00n2/Cartello_Mostra_Ombrello_Small_tif

Interestingly, if levels are flattened before export conversion is carried out.

**Comment by pcholuj** [comment]
hi @gsdefender 
Can you provide some more information about how you are converting this file? Are you using it as an external link or its uploaded first?

**Comment by pcholuj** [comment]
Hi. After some research, your tiff file have wrong hex signature
Correct signature for tifs (based on https://en.wikipedia.org/wiki/List_of_file_signatures )
```
49 49 2A 00
# or
4D 4D 00 2A
```

Your file signature is 
```
49 49 20 20
```

**Comment by gsdefender** [comment]
> hi @gsdefender
> Can you provide some more information about how you are converting this file? Are you using it as an external link or its uploaded first?

It is uploaded first

**Comment by gsdefender** [comment]
> Hi. After some research, your tiff file have wrong hex signature
> Correct signature for tifs (based on https://en.wikipedia.org/wiki/List_of_file_signatures )
> 
> ```
> 49 49 2A 00
> # or
> 4D 4D 00 2A
> ```
> 
> Your file signature is
> 
> ```
> 49 49 20 20
> ```

I understand this, but the file is generated as so by Photoshop CS4. When you export it after levels have been flattened, it is correctly generated. Moreover, as the file is generated this way and can be opened with image viewers, the average user might not be aware of the difference in signature and won't understand why the conversion fails.
