### ISSUE TITLE
Error: "invalid params: parts"

### ISSUE THREAD

**Issue by AndraPopazu** [filestack/filestack-js#266]
I'm trying to integrate Filestack in my angular application but i'm getting  "invalid params: parts" from https://upload.filestackapi.com/multipart/complete request. I can't find anything in the docs about the "parts" param.

**Comment by pcholuj** [comment]
Hi @AndraPopazu 
Are you using your own bucket in store options? If so, can you check your s3 settings? Its probably because you don't have exposed header ETag.

**Comment by AndraPopazu** [comment]
That did the trick. Thanks @pcholuj

**Comment by pcholuj** [comment]
Np :) i added more readable error message for this issue :)
