### ISSUE TITLE
Troubles with PPT transformations

### ISSUE THREAD

**Issue by AndrewShkoda** [filestack/filestack-js#268]
When I'm trying to transform some of my PPT's with "output: { docinfo: true }" parameter, I'm getting error "conv20 provider error: The conversion is taking too long... corrupted or too large file provided (idx 0)". But the same PPT's could be successfully uploaded by the others persons.
For example: presentation with 21 slides and 441 kB.
Also this error occur with any presentation uploaded with IE11.

**Comment by pcholuj** [comment]
hi @AndrewShkoda 
Can you contact our support? We need more information about PPT file and your apikey.
