### ISSUE TITLE
Question. Transform PPT slides to PNG/JPG without resize

### ISSUE THREAD

**Issue by AndrewShkoda** [filestack/filestack-js#269]
When I transform slide of PPT with "output: { format: 'png', page: 1 }" parameters I will get image with 720x540px dimensions. For instance: If I set resize property for width with bigger value I will get image with kind of blur and lower quality.
How can I get image with original dimensions and quality?

**Comment by gr00by87** [comment]
You can use the density parameter https://www.filestack.com/docs/api/processing/#file-type. The default density, if not explicitly set, is 72. The higher the value of density, the larger the output image will be, e.g. if you set the density to 144 for the file you were testing, the output image should be 1440x1080px large.

**Comment by AndrewShkoda** [comment]
@gr00by87 Thank you very much! This works.
