### ISSUE TITLE
onFileSelected() doesn't triggers if the built-in validation fails

### ISSUE THREAD

**Issue by SasSam** [filestack/filestack-js#27]
Hi,

I tried the javascript picker, but seems like it's not possible to set a custom error message to show if the user try to upload a not accepted file type. The issue -I think- is that `onFileSelected()` is triggering after the internal validation. So even if I set the `onFileSelected()` as following:

    onFileSelected: function (file) {
        if (acceptedFileTypes.find(file.mimetype)) {
            throw new Error('Only .pdf, .txt, .rtf, .doc, .docx and .odt file types are allowed');
        }
    },

I get the built-in error message from the filestack. It doesn't work properly. The [example](https://www.filestack.com/docs/javascript-api/picker-examples-v3) (Prevent users from uploading certain types of files) on the page allows all images, but if the user select a PNG, it shows error message. But why?! Doesn't make any sense. If the user drag and drop any file it will shows the built-in error message first. And then if drag and drop an image, it revalidate on 2nd stage if it's a png or not and then we can show custom error message. But the built-in error message is not modifiable. 

I think the issue is the order of the methods here:

    if (fileIsAcceptable(normalizedFile) && fireOnFileSelected(normalizedFile) && fileIsSmallEnough(normalizedFile)) {

The `fileIsAcceptable()` is the first, which is generating the built-in error message. And if that is failing, we won't get a chance to trigger our custom validation.

Now the only way to use our custom validation is if we don't set anything in the "`accept`" config option and we do the "soft-validation" after the file was selected. Bu in this case the file-list won't be filtered on different providers.

**Comment by velveteer** [comment]
As of 0.7.0 the `onFileSelected()` callback is triggered first in the file validation logic.
