### ISSUE TITLE
the use of @sentry/minimal is intrusive and messes with globals

### ISSUE THREAD

**Issue by mlipscombe** [filestack/filestack-js#271]
The use of `@sentry/minimal` causes globals like `document`, `console`, `fetch` and others to be wrapped outside of the library, messing up callstacks for debugging.  Could this pollution of globals be made optional please?

**Comment by pcholuj** [comment]
HI. 
We will look into it.

**Comment by AndrzejSala** [comment]
@mlipscombe 
We disabled capturing of global error handlers outside the Filestack file picker app in the newest 3.6.0 version, so please check it out.

**Comment by mlipscombe** [comment]
The new version still has the same problem -- it monkey patches globals like `console`, `fetch`, `history`, `XMLHttpRequest` for Sentry's breadcrumbs.  IMHO, no library should ever monkey patch globals without it being explicitly documented, and explicitly necessary for the operation of the library.

**Comment by pcholuj** [comment]
Sentry minimal did not patch globals, but sentry for browser does So if you are not using picker but clean filestack sdk it should work.
