### ISSUE TITLE
Picker crash if there is no file extension

### ISSUE THREAD

**Issue by SasSam** [filestack/filestack-js#28]
Hi,

I set the accepted file types in "`accept`" config settings like this:

    accept: ['.pdf', '.txt', '.rtf', '.doc', '.docx', '.odt']

The Google Drive lists all related documents. Which is fine. But! If you create a new Google Document, which normally doesn't have file extension, but it's still a document, so it will be shown in the file list. But if you select a document like this, the filepicker will throw a console error:

    picker.es2015.js:8277 Uncaught TypeError: Cannot read property '0' of null
      at lp (https://static.filestackapi.com/v3/filestack.js:8:5071)
      at dp (https://static.filestackapi.com/v3/filestack.js:8:5144)
      at https://static.filestackapi.com/v3/filestack.js:8:5241
      at Array.some (native)
      at pp (https://static.filestackapi.com/v3/filestack.js:8:5203)
      at https://static.filestackapi.com/v3/filestack.js:8:26858
      at i (https://static.filestackapi.com/v3/filestack.js:8:27052)
      at Array.<anonymous> (https://static.filestackapi.com/v3/filestack.js:3:13452)
      at Pd.dispatch (https://static.filestackapi.com/v3/filestack.js:7:25874)
      at Pd.dispatch (https://static.filestackapi.com/v3/filestack.js:7:24921)

Related bug: #20

**Comment by velveteer** [comment]
@SasSam Thanks for reporting this!

I think this can go two ways: either we accept files without extensions or deny them. The files in the Google Drive list aren't actually filtered based on the accept extensions, but this could also solve the problem if we hid files without extensions.

In any case we'll get that TypeError cleared up. But let us know if you have any thoughts on desired behavior here.

**Comment by SasSam** [comment]
As the Google Doc is a normal doc and in my case I have to accept it. The way how I use this and the picker is not crashing is the following:

    accept: ['application/vnd.google-apps.document', 'application/pdf', 'application/msword', 'text/plain', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/rtf', 'application/vnd.oasis.opendocument.text', '.pdf', '.txt', '.rtf', '.doc', '.docx', '.odt']

But in this case the "not supported file type" error message will be unreadable and ugly as the built-in validation's message is not modifiable... 

Please check uploaded screenshot about the error message: https://ibb.co/fXgosk

Related issue: #27
