### ISSUE TITLE
Dropbox thumbnails are broken

### ISSUE THREAD

**Issue by cruzlutor** [filestack/filestack-js#283]
Hello, we are getting broken image thumbnails on dropbox picker gallery.

![Screen Shot 2019-08-30 at 3 41 12 PM](https://user-images.githubusercontent.com/1368971/64047543-122ea080-cb3d-11e9-9008-80caed7142d4.png)
 
We are using the last version `3.7.0`, this is also happening in the JsFiddle demos
Could be this a dropbox issue?

thanks in advance

**Comment by pcholuj** [comment]
Hi, 
For now, we don't have this feature in our API, I can make a feature request to our backend engineer
