### ISSUE TITLE
Missing disableStorageKey for client.upload function

### ISSUE THREAD

**Issue by GODBS** [filestack/filestack-js#284]
We are currently integrating filestack with our application and we ran into an issue. We are using both the picker as well as the client.upload fonction, and it seems that the disableStorageKey parameter is missing in the client.upload function. Is there another way to bypass the storage key for the client.upload function?

Thanks in advance for your answer.

**Comment by pcholuj** [comment]
Hi 
Now disableStorageKey is also available in client library.
