### ISSUE TITLE
"Something went wrong" in IE11

### ISSUE THREAD

**Issue by ksntcrq** [filestack/filestack-js#288]
Hey,

In IE11, when using filestack through filestack-react 3.0.0, the pop-up to log in to Google Drive / Dropbox keeps saying "Something went wrong" with a "Retry" button.

**Comment by Johnsoct** [comment]
I can confirm this is happening in Firefox, as well.

Here are my picker options:
```
filestackPickerOptions: {
        accept: '.pdf',
        allowManualRetry: true,
        fromSources: ['local_file_system', 'googledrive', 'dropbox', 'gmail'],
        maxFiles: 5,
},
```

**Comment by maryfs** [comment]
@Johnsoct thanks for config, we will fix it soon.

**Comment by maryfs** [comment]
@Johnsoct could you try to reproduce it on newest versions (fs-js and react)?
Because i was able to reproduce it some time ago, but now I cant.
Thanks
