### ISSUE TITLE
Wrong button labels in spanish

### ISSUE THREAD

**Issue by josemontesp** [filestack/filestack-js#289]
The spanish buttons for connecting to Facebook and Instagram are displaying the wrong message

<img width="541" alt="Screen Shot 2019-10-01 at 12 07 41 AM" src="https://user-images.githubusercontent.com/6934126/65941664-6ea50a00-e3e0-11e9-8847-b8ac6bc9d1f3.png">
<img width="560" alt="Screen Shot 2019-10-01 at 12 07 54 AM" src="https://user-images.githubusercontent.com/6934126/65941675-72389100-e3e0-11e9-82b1-764f5c356913.png">

**Comment by josemontesp** [comment]
Found a workaround. You can specify custom UI text, for some reason, using this method the providerName gets replaced correctly

```typescript
const options: PickerOptions = {
  accept: ['image/*'],
  customText: {
    'Connect {providerName}': 'Conectar {providerName}',
  },
  lang: 'es',
};
filestackClient.picker(options).open();
```

**Comment by pcholuj** [comment]
Hi 
this is fixed in new version.
Thanks
