### ISSUE TITLE
Filestack with Angular 8 and strange warning to CLI

### ISSUE THREAD

**Issue by mixalistzikas** [filestack/filestack-js#292]
I'm getting a strange warning when adding filestack

    import * as filestack from 'filestack-js';

Main code

    filestack.init(KEY, {
        security: {
            policy: 'XXX<policy>XXX',
            signature: 'XXX<signature>XXX'
        }
    });

And when I call filestack I'm getting the following warning to cli

    WARNING in ./node_modules/filestack-js/build/module/lib/utils/index.js 174:22-35
    Critical dependency: the request of a dependency is an expression

(If I just include filestack without the actual initialization I don't get the warning)

Everything works as expected.... only this annoying warning

**Comment by bradjenn** [comment]
I'm also getting this issue

**Comment by carsonaaberle** [comment]
I am having this issue with React as well.

Versions:
React: 16.10.2
filestack-js: 3.8.0

I am also using the react-filestack package as well version 3.1.0.

**Comment by anarian** [comment]
I'm encountering this issue as well, but when trying to load that mounts the Filepicker, it causes the browser to go into an infinite loop loading something from Webpack and crash the tab.

`react: 16.9.0`
`filestack-js: 3.8.0`
`webpack: 4.38.0`

Downgrading to `filestack-js:3.7.0` resolves the issue. This is _not_ using the react-filestack library.

**Comment by mickdelaney** [comment]
Also have this issue, with angular 8.

**Comment by adityatyagi** [comment]
If you are using Angular 7, uninstall the current version of filestack-js and re-install version 3.7.0.
1. `npm uninstall filestack-js`
2. `npm install filestack-js@3.7.0`

The warning goes away as well as `ng build --aot --prod` runs perfectly i.e the build runs without any warnings or errors.

**Comment by mickdelaney** [comment]
error does go away for me.

**Comment by pcholuj** [comment]
Hi. Yes this should be working :) thanks for reporting
