### ISSUE TITLE
IE11 transpiled code syntax error on 3.8.0

### ISSUE THREAD

**Issue by cruzlutor** [filestack/filestack-js#293]
Hello, we are getting a syntax error on IE11 in the latest filestack version `3.8.0`

```
SCRIPT1002: Syntax error
const toBytes = s => [...s].map(c => c.charCodeAt(0));
```

The error is caused by the spread operator, when we return to version `3.6.0` the error disappears

**Comment by pcholuj** [comment]
Hi this error should be fixed in newest version. Tested on latest IE11
