### ISSUE TITLE
multiUpload takes just as long, if not longer then calling upload multiple times

### ISSUE THREAD

**Issue by ryan-snyder** [filestack/filestack-js#296]
Recently decided to try out multiupload instead of calling upload multiple times. To my suprise, not only does multiupload take just as long if not longer but the amount of network calls are also basically the same. I'm curious what the point of multiupload is if from what I can tell there's no difference from upload?

**Comment by pcholuj** [comment]
Hi. 
Yes all requests are the same, but you can set concurrency for multiupload and in the feature, we will add a possibility to add multiple cancel tokens.

**Comment by ryan-snyder** [comment]
So would you recommend using multiupload? Currently we do:
```js
return Promise.all(files.map(filestack.upload)
```
Would it be better to do filestack.multiupload with concurrency?

**Comment by pcholuj** [comment]
its depend on your usecase
ie: in browser you have a limit for max request count ie for chrome it will be 6 per domain, so you have more control over request count and you can pause/resume/cancel all requests using one function provided in the token.
