### ISSUE TITLE
Issue with laravel and cors policy since 3.8.0

### ISSUE THREAD

**Issue by lk77** [filestack/filestack-js#297]
Hello,

i have cors errors on 3.8.0 that i don't have on 3.7.0,
it says that header X-Requested-With or header X-CSRF-Token are forbidden.

the request is going to https://upload.filestackapi.com/multipart/start

with 3.7.0 : 
![Screenshot from 2019-10-23 09-53-19](https://user-images.githubusercontent.com/9606882/67380393-8a886f80-f58a-11e9-8c01-c851d6ee9e41.png)

with 3.8.0 :
![Screenshot from 2019-10-23 09-54-06](https://user-images.githubusercontent.com/9606882/67380406-8d836000-f58a-11e9-99ee-02d52d86e17a.png)

those defaults headers are set in bootstrap.js by laravel,
but they shouldnt leak to your axios instance, and be sent to filestack

https://github.com/laravel/laravel/blob/f73795ac0569554d3464eecb259aef0d2dc64f72/resources/js/bootstrap.js

Thanks.

**Comment by pcholuj** [comment]
We cannot accept custom headers because of cors security, so you have to remove that header from request.

**Comment by lk77** [comment]
Hello,

so don't send those headers

**Comment by lk77** [comment]
Hello,

any news on this ?

i would like to update filestack but it's not possible for now due to this issue

**Comment by pcholuj** [comment]
Yes we removed axios because of mem leak problems. So it should be fine in new versions
