### ISSUE TITLE
When upload a file mimetype field sometimes is undefined.

### ISSUE THREAD

**Issue by anapanadero** [filestack/filestack-js#300]
I have created a simple example where it happens: https://stackblitz.com/edit/angular-filestack

The same file, same browser but different machine the result is different. Sometimes mimetype field is filled properly and sometimes is undefined.

Example of the environments where the result is undefined:

- Environment  1:
 - - Windows 10 Home version 1803 (OS build 17134.1069) 64-bit
 - - Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
 - - File XXX.pptx

- Environment  2:
 - - OS X 10.15.0
 - - File XXX.pptx

**Comment by pcholuj** [comment]
We are now checking magicbytes first, then file extension. It should work in current version
