### ISSUE TITLE
Format in TransformOptions probably should be optional

### ISSUE THREAD

**Issue by molszanski** [filestack/filestack-js#306]
https://dev.filestack.com/apps/AvtrNPNMNQOew6lMeFUvNz/transform/
https://github.com/filestack/filestack-js/blob/a8b496fa993a0a4998cea99cabaa5cf08407db32/src/lib/api/transform.ts#L347
```ts
  output?: {
    format: string;
    colorspace?: string;
    strip?: boolean;
    quality?: number;
    page?: number;
    compress?: boolean;
    density?: number;
    background?: string;
    secure?: boolean;
    docinfo?: boolean;
    pageformat?: string;
    pageorientation?: string;
  };
```

**Comment by pcholuj** [comment]
Yes, you have right. It will be fixed in next release

**Comment by molszanski** [comment]
Looking at the latest release it is fixed. Thnx
