### ISSUE TITLE
Minify picker's css and js sources

### ISSUE THREAD

**Issue by darkowic** [filestack/filestack-js#307]
Both CSS and js picker resources are not minified. When it is smaller the picker loads faster.
https://static.filestackapi.com/picker/1.11.0/main.css
https://static.filestackapi.com/picker/1.11.0/picker.js

**Comment by pcholuj** [comment]
Hi
Picker assets are minimalized correctly in new version

**Comment by darkowic** [comment]
@pcholuj new problem :/  Js files have included inline source maps which makes the file even bigger:
Prev: 847 KB
Now: 2.1 MB

https://static.filestackapi.com/picker/1.12.0/picker.js

Make sure the source maps are emitted as external files.
