### ISSUE TITLE
Record video and audio cannot be uploaded

### ISSUE THREAD

**Issue by bdthinh** [filestack/filestack-js#309]
Hi,
Look like record video and audio cannot be uploaded properly. 
Although this functionality is introduced with supported api, but any recorded video/ audio doesn't have size and cannot be uploaded properly.

filestack-js config
```js
const OPTIONS = {
  accept: ['video/*'],
  maxFiles: 1,
  transformations: {},
  uploadInBackground: false,
  fromSources: ['video'],
  maxSize: 10 * 1024 * 1024,
};
```
After recording video successfully, file appears without size.
![Screenshot 2019-12-06 at 23 39 12](https://user-images.githubusercontent.com/4838237/70335113-a36e8b00-1881-11ea-9ea4-dcccf5308177.png)

onSuccess callback return `filesFailed` as following
```js
{
  filename: "recording-Dec 6, 2019, 11:31 PM.mp4"
  handle: undefined
  mimetype: "video/mp4"
  originalPath: "/a0f2c42e-7e27-43e0-bf4a-ff56dd511d93/recording-Dec 6, 2019, 11:31 PM.mp4"
  size: null
  source: "video"
  uploadId: "Ug414pRx7nzzfi70"
  url: undefined
}
```
Environment
```
macOS Mojave
filestack-js v3.10.1
```

**Comment by maryfs** [comment]
Hi @bdthinh ,
for some reasons i can't reproduce this bug, however the problem is that even if i set maxSize i can record video without any limits and then successfully upload it.
Could you tell me on which browser you test it?
Thanks.

**Comment by mhoughton11** [comment]
@bdthinh I was having this issue and getting that exact response when using the `onUploadStarted` callback but I changed to using the `onFileUploadFinished` I was getting the preferred response with all the required data. Granted this is fired after an upload finishes as opposed to when it starts which may be different to your needs but worked for me.
