### ISSUE TITLE
HTTP Error 500 after upload

### ISSUE THREAD

**Issue by gsdefender** [filestack/filestack-js#31]
Hi, 
I have been experiencing problems trying to upload several images, the Filestack endpoint always 
returning HTTP Error 500.

This problem is reproducible using this public domain image file:

https://it.wikipedia.org/wiki/File:Antonello_da_Messina_-_Portrait_of_a_Man_-_National_Gallery_London.jpg

**Comment by velveteer** [comment]
Hey @gsdefender, thanks for reporting this. Can you provide some clarity on how you are uploading that file? Can you provide a code example or steps to reproduce?

**Comment by gsdefender** [comment]
Sure.
I am uploading that file (or the other files whose process ends in error) from a copy I have on my hard drive. I can post a Codepen of the relevant code if you think  it might help, but apart from the fact that I am using a (rather liberal) security policy for the instance my client, it is not much more than the standard example you find on the docs

**Comment by gsdefender** [comment]
I have prepared a Codepen: https://codepen.io/gsdefender/pen/weOpPW
I have used one of the test API keys I've found in the documentation examples.
If you try to upload the aforementioned file (Antonello da Messina's portrait of a man, found on Wikipedia), the upload will seem to end well, but you get an HTTP Error 500 instead if you open the browser console.

**Comment by velveteer** [comment]
@gsdefender Thanks for the example. I eventually reproduced the 500 error, but the upload retried and then completed successfully. Curiously the 500 is coming from S3, and I failed to reproduce the 500 on another key. 

I will raise this issue with our backend engineers, they would have more insight on the possible causes here.

**Comment by gsdefender** [comment]
Thank you very much. So, while the backend engineers sort out the problem, my problem is that in my code I'm not able to detect the event of a failed, then successfully retried upload, so I can't use the URL. I'm using the onFileUploadFinished callback. Did I miss something in the docs, or do you have any suggestion to work around this? Thanks again

**Comment by maryfs** [comment]
cannot reproduce with 2.x.x.
