### ISSUE TITLE
Is ".pdf" really for accepting any filetype?

### ISSUE THREAD

**Issue by IanVS** [filestack/filestack-js#311]
The docs (https://github.com/filestack/filestack-js/blob/6987bc6/src/lib/picker.ts#L361) say to use `".pdf"` for any file extension, but that doesn't seem right.  I would have expected `*/*` for any (I guess it has to be omitted, based on https://github.com/filestack/filestack-js/issues/80), and `.pdf` for pdf files.  Any clarity would be appreciated.

**Comment by maryfs** [comment]
Hi,
it's an example file extension  , if you want to accept any type of file, just skip 'accept'.
