### ISSUE TITLE
Allow customizing dropPane

### ISSUE THREAD

**Issue by IanVS** [filestack/filestack-js#312]
Previously, `makeDropPane`, when given a container, did not render its own UI, but rather it used the container it was given.  I can't seem to figure out how to replicate that behavior, is it even possible?  I see that I can do things like change the text, or turn on/off a preset icon, but I can't set my own icon, or change any of the other styles without some really hacky CSS.  Am I doing something wrong, or is it just no longer possible? Thanks!

**Comment by maryfs** [comment]
Hi @IanVS ,
whats the version it worked for you ? 
Could you share some code?
Thanks.

**Comment by IanVS** [comment]
I upgraded from `api.filepicker.io/v2/filepicker.js` to `static.filestackapi.com/filestack-js/3.x.x/filestack.min.js`.  

I can't share much code, but what I had before was `filepicker.makeDropPane(this.$('.drop-overlay'), this);` inside a backbone view.  Back then, filepicker drop panes didn't come with its own UI, so I could just do that and then build the pieces of UI that I needed.  That doesn't seem to be possible anymore.

**Comment by pcholuj** [comment]
You can still customize it by using your css attributes, You cna use container property in picker config
ie: 
container: document.querySelector('#inline'),
