### ISSUE TITLE
Unguarded `Symbol` in filestack.min.js

### ISSUE THREAD

**Issue by IanVS** [filestack/filestack-js#317]
I am loading `//static.filestackapi.com/filestack-js/3.x.x/filestack.min.js` in a script tag in my app, and I find that it is crashing in IE11, seemingly from a reference to `Symbol` without checking first for its existence.  The part of the minified code where this happens is line 34, column 23994:

```
function _iterableToArray(e){if(Symbol.iterator in Object(e)||"[object Arguments]"===Object.prototype.toString.call(e))
```

I can't find an official list of supported browsers, but I assume that IE11 is one of them, right?  Think you could push a new version that supports ES5?  Thanks!

**Comment by maryfs** [comment]
Hi,
If you target IE11  you will need to add additional polyfills.
https://filestack.github.io/filestack-js/#polyfills
List of supported browsers: https://filestack.github.io/filestack-js/ check the labels ;)

**Comment by IanVS** [comment]
Ah, thanks!  I tried searching in https://www.filestack.com/docs/ without any luck.  And I read https://filestack.github.io/filestack-js/#browsers but it didn't mention supported browsers.  I guess I didn't look deep enough.  Thanks again.
