### ISSUE TITLE
Can't resolve `fs` in 3.11.0 `filestack-js\build\module\lib\api\upload`

### ISSUE THREAD

**Issue by Cherry** [filestack/filestack-js#319]
After updating to the latest version, our webpack build is failing with:

```
Module not found: Error: Can't resolve 'fs' in '...\node_modules\filestack-js\build\module\lib\api\upload'
```

Downgrading to 3.10.1 resolves the issue.

**Comment by reubenharcourt** [comment]
Same error and fix here

**Comment by DmitriyGribennikov** [comment]
have the same error today

**Comment by pcholuj** [comment]
Hi
Sorry we are working to resolve this issue. For now please use previous version of filestack-js.

**Comment by noisy** [comment]
it looks like downgrade to 3.10.1 is not enough.

https://github.com/filestack/filestack-js/compare/v3.10.0...master

For me downgrade to `"3.10.0"` resolved the issue.

**Comment by Cherry** [comment]
Just to confirm, upgrading to the newest release, `3.11.1`, still seems to have the issue.

**Comment by burningalc** [comment]
I have run into the same issue when building the webpack too. Can you guys share the version number which has no "fs" error? Thanks.

**Comment by Cherry** [comment]
> I have run into the same issue when building the webpack too. Can you guys share the version number which has no "fs" error? Thanks.

`3.10.1` is the latest version that works for us, though some have reported having to downgrade to `3.10.0`.

**Comment by frogamic** [comment]
I have also encountered this issue, rolling back to 3.10.1 worked for me.

**Comment by pcholuj** [comment]
Hi, sorry there was a problem with local linking package. new Release 3.11.2 should fix the problem. Tested with webpack. @Cherry can you confirm?

**Comment by Cherry** [comment]
I can confirm 3.11.2 is working fine for us now. Thanks @pcholuj!
