### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by kevadiya93** [filestack/filestack-js#322]
`Uncaught TypeError: _super.call is not a function
    at new S3Uploader (modules.js?hash=2f014ac99a66785a25c384c175303e84ed40ac8e:72715)
    at new Upload (modules.js?hash=2f014ac99a66785a25c384c175303e84ed40ac8e:72485)
    at Client.upload (modules.js?hash=2f014ac99a66785a25c384c175303e84ed40ac8e:75406)`

wen try to upload file.

**Comment by maryfs** [comment]
Hi @kevadiya93 
which version do you use? also please submit sample code.
Thanks

**Comment by kevadiya93** [comment]
Hi @maryfs,

I am using latest version 3.x.x ( 3.11.1 )
`import * as filestack from 'filestack-js'
const client = filestack.init(apikey)

const onProgress = (evt) => {
  console.log(`${evt.totalPercent}%`);
}
client.upload(file/url, { onProgress }, { }, { })
      .then(res => {
        console.log('success: ', res)
      })
      .catch(err => {
        console.log(err)
      })
`

Thanks

**Comment by maryfs** [comment]
thanks @kevadiya93 ,
if you want to store url, you should use `client.storeURL(url)` https://filestack.github.io/filestack-js/globals.html#storeurl, 
for file use raw file : https://filestack.github.io/filestack-js/globals.html#rawfile

also you may want to try newest version 3.11.2,
let me know if it works.

**Comment by kevadiya93** [comment]
Hi @maryfs ,

Using newest version 3.11.2, and with `client.picker(options).open()` works.

Thanks
