### ISSUE TITLE
Error in edge, "Function expected"

### ISSUE THREAD

**Issue by IanVS** [filestack/filestack-js#324]
When uploading files in Edge 17, I'm getting an error of `Function expected` with no further details in my `onFileUploadFailed` callback.  I specifically checked the `details` of the error, and it's undefined.  It sounds like maybe a `File` constructor is being used, which is not supported in IE or Edge.  Ref: https://stackoverflow.com/a/52885069/1435658

I have `polyfill.io/v3/polyfill.min.js?flags=gated` in my `head`, but apparently that does not provide a File api polyfill.  Caniuse suggests https://github.com/moxiecode/moxie.  Do I need to add that too?  Or maybe you can compile the filestack code down to something that Edge supports?

Edit: I took a quick look at moxie and it kind of looks like a nightmare to set up.

**Comment by pcholuj** [comment]
Hi @IanVS 
Fix will be released soon. We changed initialization of File object so problem should be fixed without polyfill

**Comment by IanVS** [comment]
Wonderful, thank you!

**Comment by pcholuj** [comment]
Hi
New version was released yesterday so this problem should be fixed
