### ISSUE TITLE
onProgress not work for node.js

### ISSUE THREAD

**Issue by comus** [filestack/filestack-js#328]
i use the same code with the filestack-js node.js example

the current version 3.x.x not work, the totalPercent always zero and 100

then i use the old version which 1.0.0-rc1. and it works.

**Comment by pcholuj** [comment]
Hi @comus 
Probably we will add support for node progress. It's adding more complexity to our new request library so we need to do it step by step to not break anything.

**Comment by pcholuj** [comment]
Hi progress event should work now for nodejs, check the latest release
