### ISSUE TITLE
onFileUploadFinished only after "Upload" click

### ISSUE THREAD

**Issue by rmartins90** [filestack/filestack-js#33]
I intend to trigger a method only when user clicks "Upload" button. How's this possible? onFileUploadFinished callback has nothing to do to this.

**Comment by velveteer** [comment]
@rmartins90 We have a feature in the backlog for something like `onUploadStarted` which would trigger on the upload initialization. I believe the intention is to call back with a list of all the files queued for upload, as opposed to the `onFileUploadFinished` callback which is per file. 

Right now there's no way to hook into uploads starting outside of `onFileUploadStarted` but that is per file. I will look into getting this feature in the next release.

**Comment by velveteer** [comment]
@rmartins90 0.9.0 now includes the `onUploadStarted` callback and is documented in the readme. It will trigger whenever a user starts the upload (by clicking the Upload button).
