### ISSUE TITLE
Issue with latest 3.12.x version and "Zi is not defined" issue in file picker

### ISSUE THREAD

**Issue by cdrum** [filestack/filestack-js#332]
We were pulling the /3.x.x/filestack.min.js, and found that the picker stopped working the last day or so - when dragging an image into the popup, the spinner would just endlessly spin.

Looking at the console, we found a few errors stating "Zi is not defined"

If we hard code version 3.11.2, then this error goes away.

![2020-02-14_16-47-06](https://user-images.githubusercontent.com/119126/74526830-3dba1180-4f4a-11ea-9cb1-fa3246e0ad32.png)

**Comment by maryfs** [comment]
Hi @cdrum ,
could you share your picker configuration?
Thanks.

**Comment by maryfs** [comment]
Fix done on latest version 3.12.4.
@cdrum  let us know if it works for you.

**Comment by cdrum** [comment]
Hi thanks! Will check probably tomorrow to see if this fixes for us. thanks for your fast response!!!

**Comment by cdrum** [comment]
Wonderful, the fix for version 3.12.4 works !! thanks!
