### ISSUE TITLE
Gmail and dropbox integraton issue.

### ISSUE THREAD

**Issue by TomekStaszkiewicz** [filestack/filestack-js#338]
version: 3.10.1
browser: Google Chrome

The dropbox and gmail integrations fail. It displays   `Something went wrong`. 

You can find the same bug on [filestack official website](https://www.filestack.com/docs/concepts/pickers/web/)

Reproduction:

1. Include 
`<script src="//static.filestackapi.com/filestack-js/3.x.x/filestack.min.js"></script>` 
in code
2. Configure client with: 
`const client = filestack.init(YOUR_API_KEY);
client.picker().open();`
3. You can notice that dropbox integration doesnt work as expected.
![a](https://user-images.githubusercontent.com/46328998/76083685-70d24c80-5fae-11ea-9f8d-c4a3f9741cac.png)

**Comment by horaciosystem** [comment]
@TomekStaszkiewicz Did you solve the error somehow?

**Comment by TomekStaszkiewicz** [comment]
@horaciosystem Yes, I did. It turned out that the API integration for Dropbox and Gmail changed a little. You can find more info [here]( https://www.filestack.com/docs/concepts/pickers/web/#sources-list)
