### ISSUE TITLE
Typo on TransformOptions parameter: "localion"

### ISSUE THREAD

**Issue by bern** [filestack/filestack-js#342]
Noticed this while trying to implement a storage flow within my transformation. Looks like there's a typo in this parameter:

https://github.com/filestack/filestack-js/blob/a8b496fa993a0a4998cea99cabaa5cf08407db32/src/lib/api/transform.ts#L199

`localion` should be `location` according to the docs here: https://www.filestack.com/docs/api/processing/#store . Not sure if this affects the functionality of the storage mechanism, but just thought I would point it out!

**Comment by pcholuj** [comment]
Thanks for info. Will fix it in next release

**Comment by pcholuj** [comment]
Fixed
