### ISSUE TITLE
"Webcam Disabled" when embedded in iFrame

### ISSUE THREAD

**Issue by DrMeers** [filestack/filestack-js#347]
e.g. https://awards.dogooder.co/impact-award-entry

<img width="316" alt="Screen Shot 2020-04-16 at 7 26 01 pm" src="https://user-images.githubusercontent.com/48157/79439410-22d24f00-8018-11ea-88fb-a86d647f4609.png">

yet it works fine if you load the iframe URL directly. Is it possible to use the webcam from within an iframe?

**Comment by DrMeers** [comment]
Also only seems to be an issue on Desktop browsers, mobile works OK

**Comment by Deskimo** [comment]
btw we have live implemenetations of the widget on urgent climate campaigns (e.g. https://www.stopadani.com/marshselfie )  which are now broken so any help you can give urgently would be appreciated FIlestack crew!

**Comment by DrMeers** [comment]
Actually, reading up on [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) and [Feature Policies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy) I think what we need is to add an `allow="camera"` attribute on the `iframe`. Weird, we were sure this was working before without that...?!

**Comment by Deskimo** [comment]
We seem to have fixed this with the additional parameter btw.

**Comment by DrMeers** [comment]
Might be worth adding to the docs somewhere though?
