### ISSUE TITLE
Multiple picker with different options not working as expected

### ISSUE THREAD

**Issue by webdev36** [filestack/filestack-js#348]
I have 2 pickers in one page.
One is for single selection and another is for multiple selection.
If I open any picker right after page reloading, it works as expected.
But after I open one type of picker (either single or multiple) another type of picker is not working as expected.
For example, here is the scenario.

- I reload the page.
- I open single file picker.
- It opens single file selection dialog.
- I close it and open multiple file picker.
- It opens single file selection dialog again instead of multiple one.

**Comment by schmoove** [comment]
We have the same issue trying to run 3x different picker configs on one page. Have tried init'ing the pickers in separate objects, but still seems to be some collision.

For example, if we have Image (image/*), Audio (audio/*), Video (video/*) pickers, the Filestack client will fix the directory mask to the first one opened. Regardless of any further pickers opened.

**Comment by schmoove** [comment]
Following on from this- we found if we create three different Filestack client objects, it works. You can't use the same client object and switch between settings it seems.

**Comment by joaopedre** [comment]
Hi @schmoove , How can I create three different Filestack client objects?

**Comment by schmoove** [comment]
@joaopedre we do it like this:

```
Syngency.filestackImage = filestack.init(Syngency.filepicker_key);
Syngency.filestackAudio = filestack.init(Syngency.filepicker_key);
Syngency.filestackVideo = filestack.init(Syngency.filepicker_key);
```

And then use:

`Syngency.filestackImage.picker(options).open()`

**Comment by joaopedre** [comment]
I'm using this js in filestack-rails gem
`https://github.com/filestack/filestack-rails`

**Comment by aldoreyes** [comment]
Had the same problem, after updating to version 3.17.0 seems to fix this without needing multiple clients.
