### ISSUE TITLE
Custom source image thumbnails are quite small

### ISSUE THREAD

**Issue by mattlewis92** [filestack/filestack-js#35]
The v2 custom source service was much easier to preview images than v3, in v3 the previews are so small you can barely see them. Would it be possible to make the preview sizes bigger? Thanks! 😄 

v2 custom source previews:
![image](https://user-images.githubusercontent.com/6425649/28170556-b28dd37c-67dd-11e7-90ed-2225527df966.png)

v3 custom source previews:
![image](https://user-images.githubusercontent.com/6425649/28170582-c01a3d50-67dd-11e7-93bb-c7c2c4837391.png)

**Comment by velveteer** [comment]
@mattlewis92 Thanks for the feedback! Would you prefer the ability to toggle between list/grid views like in v2?

**Comment by mattlewis92** [comment]
Yeah that would be perfect! 😀

**Comment by velveteer** [comment]
This should be resolved in 1.0.0-rc1. Please see the release notes here: https://github.com/filestack/filestack-js/issues/101. There is now the ability to switch between list and grid views for cloud sources.

If you feel this issue should be reopened please let us know.

**Comment by SteveJamiesonSSN** [comment]
Note this feature, but would love to be able to add it to the default options, so that a specific view is a default when opening the picker @velveteer
