### ISSUE TITLE
Rollup build is not working with filestack-js

### ISSUE THREAD

**Issue by sumit2201** [filestack/filestack-js#352]
I am using filestack-js in my react project. I am trying to make build using rollup (rollup -c), I am getting following error

[!] Error: Cannot call a namespace ('isutf8')
node_modules\filestack-js\build\module\lib\utils\index.js (108:12)
106: }
107: try {
108: if (isutf8(file)) {
^
109: return 'text/plain';
110: }
Error: Cannot call a namespace ('isutf8')
at error (\node_modules\rollup\dist\shared\rollup.js:10120:30)
at Module.error (\node_modules\rollup\dist\shared\rollup.js:14557:16)
at CallExpression$1.bind (\node_modules\rollup\dist\shared\rollup.js:11444:37)
at IfStatement.bind (\node_modules\rollup\dist\shared\rollup.js:8749:23)
at BlockStatement$1.bind (\node_modules\rollup\dist\shared\rollup.js:8745:31)
at TryStatement.bind (\node_modules\rollup\dist\shared\rollup.js:8749:23)
at BlockStatement$1.bind (\node_modules\rollup\dist\shared\rollup.js:8745:31)
at FunctionExpression$1.bind (\node_modules\rollup\dist\shared\rollup.js:8749:23)
at VariableDeclarator.bind (\node_modules\rollup\dist\shared\rollup.js:8749:23)
at VariableDeclaration.bind (\node_modules\rollup\dist\shared\rollup.js:8745:31)

**Comment by deltek-rossjackson** [comment]
Our team is also experiencing this issue.  Can someone let us know what we can do as a workaround with rollup.

**Comment by sumit2201** [comment]
Hi @deltek-rossjackson 
I have applied following setting in rollup to make it work in rollup.config.js

```
import nodeResolve from 'rollup-plugin-node-resolve';
nodeResolve({
      browser: true,
    }),

```
After that it is working as expected, hope it will help in your scenario as well

**Comment by deltek-rossjackson** [comment]
We actually just move the filestack-js as a devDependencies and peerDependencies for now and all the client apps that are using the library we have shall install it as a dependency.

**Comment by wiesson** [comment]
Same here - I'd like to use filestack-js with snowpack.dev 

```
✖ 'crypto' is imported by 'node_modules/filestack-js/build/module/lib/api/security.node.js', but could not be resolved.
  'crypto' is a Node.js builtin module that won't exist in the browser.
  Find a more web-friendly alternative, or add the "rollup-plugin-node-polyfills" plugin to your Snowpack config file.
✖ 'stream' is imported by 'node_modules/filestack-js/build/module/lib/request/utils.node.js', but could not be resolved.
  'stream' is a Node.js builtin module that won't exist in the browser.
  Find a more web-friendly alternative, or add the "rollup-plugin-node-polyfills" plugin to your Snowpack config file.
Conflicting namespaces: node_modules/filestack-js/build/module/index.js re-exports 'FilestackError' from both node_modules/filestack-js/build/module/index.js and node_modules/filestack-js/build/module/filestack_error.js (will be ignored)
Conflicting namespaces: node_modules/filestack-js/build/module/index.js re-exports 'getMimetype' from both node_modules/filestack-js/build/module/index.js and node_modules/filestack-js/build/module/lib/utils/index.js (will be ignored)
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Cannot call a namespace ('isutf8')
```

**Comment by pcholuj** [comment]
Please use rollup with resolve plugin and option browser: true
