### ISSUE TITLE
`onUploadDone` swallows errors

### ISSUE THREAD

**Issue by alizain** [filestack/filestack-js#353]
It appears that the filestack client wraps the `onUploadDone` callback in a try-catch block, swallows errors, and then re-runs the `onUlpoadDone` callback without any data.

We don't expect this kind of behaviour from the client. Is this intentional? If so, why?

Ideally, it should bubble the thrown error all the way up to the user. If you really need to wrap the callback in a try-catch block, re-running the callback with no data seems entirely non-sensical.

**Comment by sshaw** [comment]
Yes this is not good behavior.

I got an error the 2nd time the picker's `onUploadDone` callback was called  since  `filesUploaded` and `filesFailed` were both empty. 

Turns out the true error was in my upload handler but, I never saw it.

**Comment by lsirdevan** [comment]
I agree, this behavior is very frustrating. All of my uploads are coming back in the `filesFailed` response but there's no indication as to why. 

I've verified all my storage settings are correct and the files are actually being uploaded to S3 correctly, but for some reason the picker is saying the upload failed.

**Comment by pcholuj** [comment]
@lsirdevan we are trying to make better error handlers, but its take time to update all of our services.
@alizain @sshaw can you provide filestack-js version? because onUploadDone is not wrapped with any try catch block like in example: https://jsfiddle.net/20g18ruj/

can you provide some minimal reproducable example ?

**Comment by sshaw** [comment]
> can you provide filestack-js version?

3.15.0


>  because onUploadDone is not wrapped with any try catch block

Pretty sure it is. I looked into @alizain's comment and saw it for myself prior to posting my comment. 

> can you provide some minimal reproducable example ?

This does it: https://jsfiddle.net/sfn57te6/

I just removed the `displayMode: 'inline'` option and voilà
