### ISSUE TITLE
Picker in crop mode doesn't trigger correct cancel/close callback

### ISSUE THREAD

**Issue by hamfz** [filestack/filestack-js#355]
If a picker is opened via `.crop` and given a file, but the user clicks the 'Go Back' arrow, the modal is removed but no `onClose` or `onCancel` callbacks are triggered. This can result in bad consuming app states.

I am handling this currently by just removing the back arrow on my crop modal, but seems like an oversight. I tried digging into the source a bit for a better solution, but didn't make much headway

**Comment by pcholuj** [comment]
We released fix for arrow, and onClose method is not fired because drop panel is not closed, but you can use onCancel method because file upload was canceled
