### ISSUE TITLE
Italian UI translation issues

### ISSUE THREAD

**Issue by gsdefender** [filestack/filestack-js#36]
Some of the UI strings may have not been correctly translated into Italian. I have spotted these two:

1. The error message showed when the file size exceeds maxSize is in Spanish ("Arquivo é muito grande. O tamanho de arquivo aceito é" appears, instead of "Il file è molto grande. La dimensione massima accettata per i file è" or something like that);
2. The popup title when the web search source is chosen is "Scatta foto" (the Italian for "Take a photo"): a correct translation for "Web Search" would be "Ricerca sul Web".

**Comment by velveteer** [comment]
Thank you for this feedback! These changes are now available in 0.8.0.

**Comment by gsdefender** [comment]
I'm reopening this. There is another error in the image editor. "Crop" is translated into "Potare"; that's incorrect. It should be translated into "Ritaglia"
