### ISSUE TITLE
SSR issue

### ISSUE THREAD

**Issue by rgnevashev** [filestack/filestack-js#37]
Im using SSR in my app
I got error Cannot read property 'Vue' of undefined
![2017-07-21_08-41-00](https://user-images.githubusercontent.com/123600/28450490-5b3051cc-6df0-11e7-99e1-44a97bb15512.png)

**Comment by velveteer** [comment]
@rgnevashev Can you confirm what version of filestack-js you are using here?

**Comment by velveteer** [comment]
I believe SSR should be fine since 0.7.0 and we cannot reproduce any issues related to it. Based on your screenshot you may be on an older version, since Vue should not be in scope on any releases past 0.7.0.
