### ISSUE TITLE
Error uploading SVG files via filepicker

### ISSUE THREAD

**Issue by bathyscaaf** [filestack/filestack-js#372]
I've attempted to upload many different SVG files.  There doesn't appear to be anything wrong with any of them.

- The "onUploadDone" callback fires, but the file response is in a "filesFailed" array on the response, with the handle and url properties as "undefined".
- The "onFileUploadFailed" callback also fires, but the error response is an object identical to the item in the "filesFailed" array, and doesn't tell me anything useful.

Examples from one attempt below:

An example error response from the "onFileUploadFailed" callback: 
{
  "filename": "Marbles.svg",
  "handle": undefined
  "mimetype": "image/svg+xml",
  "originalPath": "Marbles.svg",
  "size": 714275,
  "source": "local_file_system",
  "uploadId": "Aif2XvFsQxGZePn2",
 "url": undefined
  "originalFile": {
    "name": "Marbles.svg",
    "type": "image/svg+xml",
    "size": 714275
  }
}

The response for "onUploadDone":
{
  "filesUploaded": [],
  "filesFailed": [
    {
      "filename": "Marbles.svg",
      "handle": undefined
      "mimetype": "image/svg+xml",
      "originalPath": "Marbles.svg",
      "size": 714275,
      "source": "local_file_system",
      "uploadId": "Aif2XvFsQxGZePn2",
      "url": undefined
      "originalFile": {
        "name": "Marbles.svg",
        "type": "image/svg+xml",
        "size": 714275
      }
    }
  ]
}

**Comment by UGrudzien** [comment]
Hi @bathyscaaf, can you please contact our Support Team (support@filestack.com)? We need to check your application settings. Thank you!

**Comment by eyalgursoy** [comment]
I'm encountering the same issue, unable to upload SVG files via the file picker, there is no clear documentation about that, why is it being blocked and how can it be fixed?
I've tried setting up a workflow, detecting file mimetype of image/svg+xml and strip the file and store it. That didn't do the trick.
I've tried contacting the support as well, and got no reply.

**Comment by pcholuj** [comment]
@eyalgursoy Hi Can u contact to our support? because all uploads od svg and html files are disabled by default for safety reason.

**Comment by masudhossain** [comment]
Still can't upload svg or xml. Huge dealbreaker for us.
