### ISSUE TITLE
Resumable uploads not working?

### ISSUE THREAD

**Issue by notbogdan** [filestack/filestack-js#387]
I'm scoping out the Filestack SDK to help pause/resume uploads in our application. I am testing the demo example [here](https://jsfiddle.net/Lj8ebohm/1/), with an API key linked to an account on the "Grow" tier, which should support resuming uploads (unless I've misunderstood the "Resumable uploads (manual)" feature listed in the second column [here](https://www.filestack.com/pricing/)). I have not been able to successfully pause/resume an upload on the latest version of the SDK on the demo - anyone has any insight as to why?

**Comment by cruzlutor** [comment]
The cancel option is not working either, we are also using the latest filestack version 3.17.0 to date

**Comment by maryfs** [comment]
Hi @notbogdan , @cruzlutor 
We  will fix this in next release. Thanks.

**Comment by maryfs** [comment]
@notbogdan and @cruzlutor  let me know if it works for you in version 3.18.0 (newest).

**Comment by cruzlutor** [comment]
@maryfs upload cancel is working in 3.18.0, thanks!
