### ISSUE TITLE
Google drive integration not working in safari 14

### ISSUE THREAD

**Issue by Maxim-Filimonov** [filestack/filestack-js#389]
I get the following error after authenticating with google drive:
![image](https://user-images.githubusercontent.com/360645/94380632-e3806080-0168-11eb-930e-a37e5f503fef.png)

Confusingly, it allows me to proceed and select a file to upload but the file never uploads and just get stuck on 0%. 
Tried the same exact steps in google chrome - no issues there.
So I do believe it's a problem with file stack library. 
Replicated on iOS 14 and Mac Safari 14 Catalina

**Comment by maryfs** [comment]
Hi @Maxim-Filimonov 
is it still a problem? we recently faced some issue with uploads.
If it still occurs, please share your sample code.
Thanks.

**Comment by Maxim-Filimonov** [comment]
It's a problem we experienced on the Kajabi platform. I'm not sure what code do they use.

**Comment by maryfs** [comment]
@Maxim-Filimonov I've checked, and this issue is already reported via our support, however it is not connected with filestack-js lib .

**Comment by Maxim-Filimonov** [comment]
What is the issue with than ?
