### ISSUE TITLE
Mimetype for keynote files are not resolved

### ISSUE THREAD

**Issue by doganyazar** [filestack/filestack-js#391]
Uploading keynote files returns mimetype: undefined.
Expected result would be `application/x-iwork-keynote-sffkey` or `application/vnd.apple.keynote`

<img width="566" alt="Screen Shot 2563-10-07 at 17 10 42" src="https://user-images.githubusercontent.com/1618686/95411568-05d86200-0951-11eb-99e7-e0be8435ad72.png">

**Comment by maryfs** [comment]
@doganyazar which version is it?

**Comment by doganyazar** [comment]
"filestack-js": "^3.5.0",
"filestack-react": "^3.1.0"

**Comment by maryfs** [comment]
@doganyazar update to the newest version (3.18.0) and let me know. We were adding this to latest release.

**Comment by doganyazar** [comment]
@maryfs I have tried it with the latest version from this link:
http://static.filestackapi.com/filestack-js/3.x.x/filestack.min.js
```
filestack.getVersion()
"JS-3.18.0"
```

And result is the same, no mimetype.

**Comment by maryfs** [comment]
@doganyazar i've checked your file, and it was stored with correct mimetype:

```
"filename": "dodo-keynote.key",
  "provider": "amazon",
  "size": 450933,
  "mimetype": "application/vnd.apple.keynote",
```
but yes, lib should return this mimetype after upload, we will fix it in next release. Thanks.

**Comment by Macavirus** [comment]
I believe this PR now release and on NPM should close this issue:
https://github.com/filestack/filestack-js/commit/669e178ef9d6cbd4d2303cec0f8cbbbf208b50fd

**Comment by maryfs** [comment]
@doganyazar  please check on v 3.20.0 and let us know. Should be fixed.
