### ISSUE TITLE
HEIC images vertically squished

### ISSUE THREAD

**Issue by chrismerritt** [filestack/filestack-js#399]
When uploading a HEIC image the Filestack module is squishing the images. See attached. 

![IMG_2984](https://user-images.githubusercontent.com/1310449/98859181-c27d8180-242f-11eb-9af5-d5b160832a87.PNG)

**Comment by pierrephilippon** [comment]
@chrismerritt  i have the same issue with picture taken vertically from mobile but not horizontally. How did you solve this issue? Thanks!
