### ISSUE TITLE
storeURL and pick have different response blobs

### ISSUE THREAD

**Issue by zimme** [filestack/filestack-js#4]
It would be nice if the result blob would have the same structure.

What I've found so far is that one command have `filename` while the other have `name`.

**Comment by velveteer** [comment]
@zimme Good catch, these responses definitely need to be normalized. I'll prioritize that for our next patch release and let you know when it's out. Thanks for the feedback!

**Comment by zimme** [comment]
p.s.
Typescript is awesome for library development. =)

**Comment by velveteer** [comment]
@zimme I am a huge fan of static type checking, which most certainly would catch issues like this. I do have a personal desire to rewrite the core API logic in something like Typescript, so maybe we can get that ball rolling at some point. :)

**Comment by velveteer** [comment]
@zimme 0.4.1 has changed the picker response shape, so `name` has become `filename`. This should be consistent with the other API calls, let me know how that looks.
