### ISSUE TITLE
onFileUploadFinished is not called

### ISSUE THREAD

**Issue by tiagofscoelho** [filestack/filestack-js#40]
Hello guys. After updating the version to 0.8.0 (regarding #34) onFileUploadFinished is not called if I select an image. The use case is:
 
1. Select an image
2. The transformer will open
3. Don't apply any changes on the image
4. Click on "Upload" button
5. Callback onFileUploadFinished is not called

This is probably happening because you do the upload in background and then when users press "upload" if there isn't any change on the image, you only close the modal. How can I get the Image URL that was uploaded?

**Comment by velveteer** [comment]
@tiagofscoelho The `onFileUploadFinished` callback is not called for background uploads, as you've noticed. You could try turning off background uploads with `uploadInBackground: false`. 

You can still retrieve uploaded file metadata from the `filesUploaded` field in the resolved promise payload, e.g. `client.pick(...).then(data => data.filesUploaded)`. This behavior is not affected by background uploading.

I don't know if we should fire this callback on upload start for every single file that was uploaded in the background, but I will think about a solution to this. For now I hope you can try some of the workarounds I have mentioned.
