### ISSUE TITLE
Uploading an image via data URI in the URL source in the file picker does not work

### ISSUE THREAD

**Issue by Cadigal-displayr** [filestack/filestack-js#407]
Trying to upload an image via the url source in the picker results in a 'Error fetching URL metadata' error banner in version `3.15.0` and an empty error banner in version `3.20.0`.
Supporting images from data-uris might be hard to implement but I think that having an error message explaining that they aren't supported would be good.

<details>
  <summary>The data URI I used to test this:</summary>

```
data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7
```
</details>

### Version 3.15.0
![image](https://user-images.githubusercontent.com/60370656/102731723-aead2f80-438c-11eb-8036-aa755a94deef.png)
### Version 3.20.0
![image](https://user-images.githubusercontent.com/60370656/102731603-5fff9580-438c-11eb-8bb0-20ddd9cc171a.png)

**Comment by maryfs** [comment]
Hi @Cadigal-displayr , we do not support data-uris , but error message will fixed.
