### ISSUE TITLE
Conflicting Sentry integration

### ISSUE THREAD

**Issue by namoscato** [filestack/filestack-js#416]
The way in which Sentry is integrated into this project is conflicting with our React application's Sentry configuration.

I think there are at least two issues, which might be related:

1. [This scope configuration](https://github.com/filestack/filestack-js/blob/v3.21.1/src/lib/client.ts#L122-L126) seems to be overriding all of our application's Sentry context as described in https://github.com/getsentry/sentry-javascript/issues/3206.

    As mentioned in `@sentry/minimal`'s [usage documentation](https://github.com/getsentry/sentry-javascript/tree/master/packages/minimal#usage):

    > it is discouraged to interfere with the event context. If for some reason your library needs to inject context information, beware that this might override the user's context values

    Is this scope configuration necessary? Would it be possible to add configuration to disable this behavior?

1. Your dependency on `@sentry/minimal@5.12.0` makes it impossible for us to upgrade to Sentry v6 as described in https://github.com/getsentry/sentry-javascript/issues/3234#issuecomment-772968903.

    While this is a [known challenge](https://github.com/getsentry/sentry-javascript/issues/3234#issuecomment-773438746) with competing Sentry instances on a page, would it be possible to upgrade `@sentry/minimal` to at least `v5.27.0`?

I'm happy to help out with both of the issues above. Let me know what you think, and thanks in advance for your cooperation!

**Comment by thinhvo0108** [comment]
I have exactly the same problem here (on using the combination Sentry + FileStack)
It has been a week, any update so far?

**Comment by namoscato** [comment]
@thinhvo0108 – glad to hear I'm not the only one experiencing this issue.

https://github.com/filestack/filestack-js/pull/417 takes a pass that _hopefully_ mitigates the first context issue, but I am unable to easily test that change. Hopefully we can get that merged soon, and then I was planning to followup with the `@sentry/minimal` dependency upgrade.

Pinging @pcholuj who seems to be familiar with the Sentry integration in this project (https://github.com/filestack/filestack-js/commit/5a53ddd75db9c41396b1c2d9c23dab5784ca2419, https://github.com/filestack/filestack-js/pull/264, https://github.com/filestack/filestack-js/pull/255)

**Comment by thinhvo0108** [comment]
Thanks @namoscato , your PR is great, however there was still another issue (I already commented on your PR: https://github.com/filestack/filestack-js/pull/417#issuecomment-779575378)

I also created another PR, I increased the Sentry version: https://github.com/filestack/filestack-js/pull/419

**Comment by namoscato** [comment]
> I also created another PR, I increased the Sentry version: #419

Thanks! Yeah, I figured that would have to happen as well.

**Comment by lobsterkatie** [comment]
FWIW, #419 is really the key here. The context stuff is really a separate issue. See https://github.com/filestack/filestack-js/pull/417#issuecomment-780072317 and https://github.com/getsentry/sentry-javascript/issues/3206#issuecomment-780026119.

**Comment by pcholuj** [comment]
Hi, this one will be added to next release

**Comment by mmahalwy** [comment]
@pcholuj any idea when the next release will be? :)

**Comment by pcholuj** [comment]
We are planning the next release this week

**Comment by mintplo** [comment]
@pcholuj the release has postponed? :)

**Comment by pcholuj** [comment]
Hi, @mintplo yes we have to postpone it to Monday. Sorry for inconvenience

**Comment by pcholuj** [comment]
Update for this was released yesterday, can you confirm that its working ok now ?

**Comment by mintplo** [comment]
> Update for this was released yesterday, can you confirm that its working ok now ?

Thanks for notification :) It works well!

**Comment by namoscato** [comment]
That resolved the issues on our end as well! Thanks for the release, @pcholuj.

**Comment by lobsterkatie** [comment]
Glad it's working now!
