### ISSUE TITLE
`onUploadDone` swallows errors

### ISSUE THREAD

**Issue by sshaw** [filestack/filestack-js#418]
Same as #353. It was never fixed. Still seeing it on 3.21.1. 

To reproduce see https://github.com/filestack/filestack-js/issues/353#issuecomment-753568823

**Comment by stephkoltun** [comment]
Is there any version number that doesn't swallow the errors?

**Comment by sshaw** [comment]
Maybe before 3.15.0 but otherwise I don't know. 

Just add a `console.log(files)` to your callback and when your code isn't working but an empty array is logged you know where to start looking 🙃

**Comment by pcholuj** [comment]
This should be fixed with latest release
