### ISSUE TITLE
"Nothing found" in Google Drive

### ISSUE THREAD

**Issue by vzaidman** [filestack/filestack-js#42]
using "react-filepicker"

![step1](https://user-images.githubusercontent.com/5188459/29018250-1678d088-7b63-11e7-8004-f54a8671bc41.png)

**Comment by cogKnitter** [comment]
Hi Vzaidman. Which version are you pulling in? Filestack-React is located here: https://www.npmjs.com/package/filestack-react

**Comment by vzaidman** [comment]
is this deprecated?
https://www.npmjs.com/package/react-filepicker

**Comment by cogKnitter** [comment]
React-Filepicker is not actively maintained. Filestack-React is.

**Comment by vzaidman** [comment]
i tried to migrate to Filestack-React today.
they are different not only in their api but also in the services that are supported. am i wrong?

**Comment by velveteer** [comment]
Closing this issue since it does not relate to filestack-js. If you need support please open a ticket with our support team and we'll glady answer your questions there.
