### ISSUE TITLE
Upload base64 image doesn't work

### ISSUE THREAD

**Issue by daviCalavera** [filestack/filestack-js#429]
Hi guys,
I have a possibly issue when tried to upload base64 string.

```
// prepare string (I've checked with online image decode and the image is ok)
const inputFile = `data:${image.mime};base64,${image.data}`;
// call client (Based on official doc):
filestackClient.upload(inputFile, { onRetry }, { filename: 'profile.jpg' }, token)
```

The upload is success but the response content-type is "text/plain" not image.
filestack response:
```
{
id: 457
fp_id: "pvuEkaCTTbKe7VFB3JBt_profile.jpg"
content_type: "text/plain; charset=utf-8"
user_id: 14043
created_at: "2021-03-30T18:20:25+02:00"
src_url: "https://d1t35hkz8sx2bl.cloudfront.net/api/file/pvuEkaCTTbKe7VFB3JBt_profile.jpg"
}
```
When I try on my browser the src_url get "Bad Request" status.

Any idea what happens?
Thanks

**Comment by pcholuj** [comment]
Hi, we need to do more investigation about this bug. I will let you know soon

**Comment by pcholuj** [comment]
We just released version 3.23.1, this should fix problems with b64 encoded images
@daviCalavera can you confirm ?

**Comment by daviCalavera** [comment]
I apologize, I forgot to mention I was using filestack-js: 3.21.1
I will update and test it.
Thanks @pcholuj  I let you know soon

**Comment by daviCalavera** [comment]
Sorry the delay, the version 3.23.1 fix problem.
