### ISSUE TITLE
Specify destination filename in pick()'s storeTo method

### ISSUE THREAD

**Issue by schmoove** [filestack/filestack-js#43]
Currently we can specify a destination path with pick.storeTo, but a hash string is always prefixed to the filename. This requires a separate storeURL call to move it to the desired filename.

Would it be possible to turn the hash prefix off in the pick.storeTo method so the uploaded file is unchanged when uploading it? This would save many hundreds of extra API calls for busy applications.

**Comment by velveteer** [comment]
@schmoove Hey Ryan, thanks for the feedback! I saw your email as well, and I already opened an issue in our backlog for this. We're going to look into providing an option that would essentially disable these hash prefixes in stored files.

**Comment by velveteer** [comment]
@schmoove 0.9.1 includes a new option for `client.pick` named `disableStorageKey`. Setting this to true will effectively disable the hash keys on stored files.

**Comment by schmoove** [comment]
Fantastic - much appreciated, thanks!

**Comment by schmoove** [comment]
@velveteer is 0.9.1 production-ready? 

Just tried a test with that version and `disableStorageKey`, and the file didnt show up in S3 when it's set to true, but would (with the hash prefix) when set to false or removed.

Any ideas? Let me know if I can provide more info.

**Comment by velveteer** [comment]
@schmoove It should be, I tested against my own S3 bucket many times. Are you passing any `storeTo` options?

**Comment by schmoove** [comment]
@velveteer using the following with pick()
```
filestackClient.pick({
    disableStorageKey: true,
    storeTo: {
	location: 's3',
        container: 'syngency-public',
        path: '3/assets/',
        region: 'us-east-1',
        access: 'public'
	}
});
```

And I do receive a successful response:
```
{
    filename: "milford.jpg", 
    handle: "vT6xy5SsRCG32Yvyc59m", 
    mimetype: "image/jpeg", 
    originalPath: "milford.jpg", 
    size: 81348, 
    source: "local_file_system", 
    url: "https://cdn.filestackcontent.com/vT6xy5SsRCG32Yvyc59m", 
    status: "Stored", 
    key: "3/assets/milford.jpg"
}
```

But the file is missing, and the Filestack url produces a bad file.

Should I open a ticket with support?

**Comment by velveteer** [comment]
@schmoove So that `key` looks right, but it seems the `container` is missing. I've attempted to reproduce this using almost identical `pick` and `storeTo` settings (everything same except container), but the file appeared in my bucket nonetheless:

```js
// pick options 
{
  disableStorageKey: true,
  storeTo: {
    location: 's3',
    container: 'filestack-us-east-1',
    path: '3/assets/',
    region: 'us-east-1',
    access: 'public'
  }
}
```

```js
{
  "handle": "uewYvKT6SIyev3a92gfL",
  "url": "https://cdn.filestackcontent.com/uewYvKT6SIyev3a92gfL",
  "filename": "IMG_6406.jpeg",
  "size": 3640140,
  "mimetype": "image/jpeg",
  "key": "3/assets/IMG_6406.jpeg",
  "container": "filestack-us-east-1",
  "status": "Stored"
}
```
This might be an issue with container settings. I encourage opening a ticket so we can verify if this is related to S3 configuration. In the meantime I will keep trying to reproduce this.

**Comment by schmoove** [comment]
`container` value is definitely present (syngency-public)

Will do though, thanks for looking into it

**Comment by cogKnitter** [comment]
This issue has been resolved @velveteer

**Comment by niemyjski** [comment]
I'm specifying a file path 3/assets/ and all my attachments are being written to an s3 blob of assets and not individual files in assets folder.
