### ISSUE TITLE
Bug - picker can't connect to Instagram

### ISSUE THREAD

**Issue by ofekudi** [filestack/filestack-js#441]
## Expected Behavior
Connect to Instagram using the web picker:
![image](https://user-images.githubusercontent.com/76157707/118819952-7ddf1100-b8be-11eb-9a97-b042431b1933.png)

## Current Behavior
After pressing Connect Instagram and completing the oAuth, the picker returns to the `Connect Instagram` page.

## Steps to Reproduce (for bugs)

1. Browse https://jsfiddle.net/filestack/cod349mz/
2. Press `Connect Instagram`
3. Press `Allow`
4. Picker won't load directory - it will return to step 2 instead

## Context
People can't pick photos from their Instagram

Thanks! :)

**Comment by pcholuj** [comment]
Hi, There was a problem with Instagram authentication api, but its seems to be resolved right now
