### ISSUE TITLE
[v3] Reopen image to edit?

### ISSUE THREAD

**Issue by ursoforte** [filestack/filestack-js#45]
The V3 Javascript API is beautiful, I upload a image, simple e after crop this. How to reopen image to edit again? crop, rotate...
(My user already has the image in the database, but I need to reopen it to crop.)

It looks like do not available on v3. Do you have forecast this for future?

**Comment by velveteer** [comment]
@sudeste Indeed this feature is planned. I don't have a specific ETA but it is probably going to land within the next month.

**Comment by bantic** [comment]
@velveteer We have a use case for this as well. Do you have an update on when the feature might land?
We'd like to open the UI with existing URLs as well as with images (javascript `File` objects/blobs) that they drag-and-drop into the browser.

**Comment by velveteer** [comment]
@bantic Hey, best I can say right now is that the work is part of our current sprint. So this should land sometime next week, and I'll update this issue when I have a better release estimate.

**Comment by bantic** [comment]
@velveteer Awesome! Thank you.

**Comment by velveteer** [comment]
To all subscribed here: 0.9.6 landed today and includes a `cropFiles` method on the client that accepts a list of Files/Blobs and/or URL strings. If you have any issues with this new option please open a new issue.

**Comment by heymartinadams** [comment]
Now that `cropFiles` has been replaced by the universal `picker` interface, @velveteer, how would one open an existing image to edit in the `picker` interface?

**Comment by velveteer** [comment]
@heymartinadams If you haven't already found it, a picker instance still offers this functionality via the `crop` method:

API ref: https://filestack.github.io/filestack-js/interfaces/pickerinstance.html#crop
JSFiddle: http://jsfiddle.net/gh/get/library/pure/filestack/filestack-js/tree/master/examples/crop

**Comment by heymartinadams** [comment]
Thanks, @velveteer!
