### ISSUE TITLE
Vite and rollup browser error when importing library

### ISSUE THREAD

**Issue by taylorthurlow** [filestack/filestack-js#458]
I'm getting what looks like the symptom of a circular dependency when loading the ESM module in a browser.

## Expected Behavior

Running the following code should import the ES module and not throw an error.

```javascript
import * as filestack from "filestack-js";
```

## Current Behavior

Running the following code:

```javascript
import * as filestack from "filestack-js";
```

Raises the following error in the browser console:

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (tslib.es6.js:25)
    at http.ts:43
    at node_modules/filestack-js/build/module/lib/request/adapters/http.js (http.ts:64)
    at __init (filestack-js.js?v=7b23504f:14)
    at request_adapter.node.ts:17
```

The problem is the usage of `Stream.Writable` when defining a class in `http.ts`. `Stream.Writable` is `undefined`. This would appear to be due to a circular dependency that rollup cannot resolve, but I'm not really sure.

## Steps to Reproduce (for bugs)

Reproduction repo is https://github.com/taylorthurlow/filestack-rollup-repro - simple instructions can be found in the README. You will need ruby installed, I used Ruby 2.7. 2.5 and 2.6 should also be fine. This repo is basically a completely unmodified Rails application. The commit history is extremely short and shows what little I need to do to get this to happen.

## Additional Screenshots

<img width="1291" alt="Screen Shot 2021-08-26 at 5 57 28 PM" src="https://user-images.githubusercontent.com/761640/131056459-6ad58dc3-ccb5-4b6c-8665-3099254e8f8b.png">

## Context

I'm just trying to use the library with Vite, which uses rollup under the hood.

## Your Environment

* Version used:  3.24.1
* Browser Name and version: Chrome 92 and Firefox 90.
* Operating System and version (desktop or mobile): macOS 11.5.2

**Comment by paultuckey** [comment]
@taylorthurlow I was able to work around this same issue by importing the built esm directly: 
```
import * as filestack from 'filestack-js/build/browser/filestack.esm';
```

**Comment by csellis** [comment]
> @taylorthurlow I was able to work around this same issue by importing the built esm directly:
> 
> ```
> import * as filestack from 'filestack-js/build/browser/filestack.esm';
> ```

Brilliant. Works for me.

**Comment by MCYouks** [comment]
Brillant! Works for me too, thanks 👍

**Comment by tcampbPPU** [comment]
> @taylorthurlow I was able to work around this same issue by importing the built esm directly:
> 
> ```
> import * as filestack from 'filestack-js/build/browser/filestack.esm';
> ```

Thanks! The fix I was looking for
