### ISSUE TITLE
default transformations on 0.9

### ISSUE THREAD

**Issue by Sitch** [filestack/filestack-js#46]
this lib is mutating my options object with a bunch of defaults.  particularly annoying is this:
```js
transformations: {
  crop:{},
  circle: true,
  rotate: true,
}
```

which leaves my uploads all failing.  please do not MUTATE my options object at the very least, and fix this.  it even overrides if i put `transformations: {}`.  garbage

**Comment by velveteer** [comment]
@Sitch 

Yeah the problem here is the granularity of the defaults. I will remove the unwanted mutations and ensure that defaults are only applied to the transformations object and none of its fields. I will let you know once we have that released.

**Comment by Sitch** [comment]
I don't understand what "granularity of the defaults" could mean in this context.  I don't see any tradeoffs for mutating fn arguments as it is code smell, plain and simple.  And it is concerning bc you guys don't publish your client library unminified or expose tests, so I am left to assume there will just be more low quality code, with more of these "granularity" problems -- whatever that means

**Comment by velveteer** [comment]
@Sitch 

I won't debate the tradeoffs of mutating arguments here, but I agree that in this case it is clearly undesirable. 

As for open-sourcing the client and picker code, that is something I would love to see eventually but it doesn't appear to be a priority yet. Your opinion alongside those of other developers helps make the case for it. 

By granularity I am referring to the configuration defaults being applied to individual fields within `transformations`, and I agree we should not be changing fields on that object when it is defined.

We have solid test coverage for these modules and I would hesitate to call any of it low quality, but I understand your frustration on this particular issue and I will address it with priority.

**Comment by Sitch** [comment]
A library mutating fn arguments isn't a debate, it's an anti-pattern, but I am happy to hear any reason you could come up with as a positive for a library that doesn't produce it's source code mutating it's function arguments (and not documenting it).  And if you think there are performance benefits, think again (https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments)

Also I am posting this bc this snippet:
```js
const client = filepicker.init(API_KEY)
const options = {
  preferLinkOverStore: true,
  accept: [
    ".pdf",
    ".doc",
    ".docx",
    "image/*",
  ],
  fromSources: [
    "local_file_system",
    "gmail",
    "googledrive",
    "dropbox",
  ],
  minFiles: 1,
  maxFiles: 1,
  maxSize: 25 * 1024 * 1024, // 25mb
  storeTo: {
    location: 's3',
  },
}
client.pick(options)
```
breaks going from v0.6 to 0.9, which is surprising for such a basic example from a lib with "solid test coverage".  Also the uploads fail (without reason i might add, which is surprising bc this library throws errors around like it owns the place).  

<img width="515" alt="screen shot 2017-08-25 at 12 44 22 pm" src="https://user-images.githubusercontent.com/2736163/29723703-99fa4034-8993-11e7-88b5-f41d1cc92048.png">

So am left to assume that at the very least, mutating a bunch of crop / circle transforms into my options argument is contributing.

**Comment by velveteer** [comment]
> A library mutating fn arguments isn't a debate, it's an anti-pattern, but I am happy to hear any reason you could come up with as a positive for a library that doesn't produce it's source code mutating it's function arguments (and not documenting it).

Fair enough.

While I did not write the pick config parser, I now realize to what extent we are mutating the options passed to pick. And it extends beyond `transformations`. This will most certainly be changed before 1.0. Thank you for bringing this up, and for the record I share the opinion that this argument mutation is heinous, whether or not it causes bugs.

**Comment by velveteer** [comment]
Arguments passed to `client.pick` should no longer be mutated in 0.9.1. Thanks again for reporting this.
