### ISSUE TITLE
[v3] Folder upload from local_file_system is broken in Safari

### ISSUE THREAD

**Issue by vlazar** [filestack/filestack-js#47]
**Version info:**
- filestack-js V3 0.9.0
- Safari 10.1.2, OS X 10.11.6

**Steps to reproduce:**
1. Open picker in Safari
1. Drag and drop folder with file(s) from `local_file_system`
1. (optional) Click Upload button.

**What is expected?**

On step 2 all files from folder should be shown in picker, similarly how it shows in Chrome for example.
On step 3 files should upload to Filestack.

**What is actually happening?**

On step 2 picker only shows folder, not all files from it.
On step 3 there is an error in browser console:
> Failed to load resource: The operation couldn’t be completed. blob:https://OUR_DOMAIN_URL/bb324f43-3db8-489e-b257-b88a081bcf9d (WebKitBlobResource error 4.)

**Comment by velveteer** [comment]
@vlazar I believe this is a current limitation of Safari, please see https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry. 

However, we should handle this better in the UI and document the exception. So I will look into this.

**Comment by vlazar** [comment]
@velveteer Ugh, you are right, Safari can't upload folders :( Thanks, closing this then since support for folder upload is very limited in browsers currently.

But yeah, it would make sense to reflect this on UI somehow.
