### ISSUE TITLE
Take photo & video options hidden when it switches to responsive mobile view

### ISSUE THREAD

**Issue by acorcutt** [filestack/filestack-js#51]
Hi, if you resize the browser and it triggers the mobile layout the photo & video options get hidden and they do not always come back if you resize back to the desktop width, usually clicking on something else like the web link tab brings them back.

Would it be possible to keep these visible if supported in the mobile layout?

v0.9.1 on chrome 60

**Comment by velveteer** [comment]
@acorcutt I think this is related to how we detect when the mobile layout is active. I believe this can be improved, so I will add this issue to our backlog and prioritize it. Thanks for reporting this.

**Comment by velveteer** [comment]
This should be resolved in 1.0.0-rc1. Please see the release notes here: https://github.com/filestack/filestack-js/issues/101. 

If you feel this issue should be reopened please let us know.
