### ISSUE TITLE
Filestack drag and drop conflicts with React DnD

### ISSUE THREAD

**Issue by mikhuang** [filestack/filestack-js#52]
It seems that something in React DnD is conflicting with Filestack's drag and drop functionality. Not sure what to do about this, just wanted to put this out there in case anyone else runs into it. 

It seems to affect other libraries too: https://github.com/react-dnd/react-dnd/issues/704

**Comment by velveteer** [comment]
Thanks for reporting this. We will look into anything we might be able to do to avoid the conflict. Is this just when you are using the picker inside of a React app that's also using react-dnd?

**Comment by mikhuang** [comment]
Yup, no matter where the root DnD context was. It worked after removing React DnD, haven't been able to figure out the exact conflict.

**Comment by jennybean** [comment]
I have experienced this issue as well. Filestack also begins to work when I remove React DnD.

**Comment by billouboq** [comment]
Any news ?

**Comment by zouxuoz** [comment]
Ping

**Comment by AndrzejSala** [comment]
It looks like it is more problem with react-dnd than filestack-js.  
react-dnd  was disabling [DataTransfer.dropEffect](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect) property in context of all website including another dnd implemented on it.
Checking history of this issue: https://github.com/react-dnd/react-dnd/issues/704 https://github.com/react-dnd/react-dnd/issues/802
https://github.com/react-dnd/react-dnd/issues/457

I have found that they probably fix it in 7.1.0 release
https://github.com/react-dnd/react-dnd/pull/1240


So my advice is check the newest version of react-dnd
