### ISSUE TITLE
FileStack 0.9.2 includes a wrapper for console that obfuscates where the message was logged

### ISSUE THREAD

**Issue by billscheidel** [filestack/filestack-js#53]
Looks like FileStack 0.9.2 includes `raven-js` for error monitoring which in turn installs a wrapper method around console (via `console.js`).  Now when I try and debug my project, every console statement prints `console.js:26` as the location whether or not it is coming from FileStack code.  This makes this version of the library unusable.

**Comment by velveteer** [comment]
@billscheidel Thanks for reporting this! 0.9.2 does include the `raven-js` library, but this problem may cause us to reconsider using it. We will look into providing a better sandbox or just remove it entirely. Our library should never contain code that wraps browser globals, so this will be marked as a high priority issue.

**Comment by velveteer** [comment]
@billscheidel I have pushed a hotfix to the picker script on 0.9.2 that should disable the options responsible for wrapping globals. Let us know if that looks any better.
