### ISSUE TITLE
POST Method Not Allowed with `writeUrl` method (S3)

### ISSUE THREAD

**Issue by MEGApixel23** [filestack/filestack-js#55]
I'm using Filestack for storing files in my S3 bucket. I'm trying to re-write file's content with a different file by providing an external url in a way, so the URL on filestack stays the same. 

When I try to call ```writeUrl()``` method filestack server returns a S3-related error response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
   <Error>
      <Code>MethodNotAllowed</Code>
      <Message>The specified method is not allowed against this resource.</Message>
      <Method>POST</Method>
      <ResourceType>BUCKETPOLICY</ResourceType>
      <RequestId>...</RequestId>
      <HostId>...</HostId>
  </Error>
```

Example of the code that I'm using:
```js
$window.filepicker.writeUrl({
  file,
  processedFile.url
  secParams
});
```

Here are bucket policy rules:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::some-bucket-name/*"
        }
    ]
}
```

Does anyone have the same issue?
Thanks.

**Comment by cogKnitter** [comment]
Hi @MEGApixel23, can you open a ticket with support@filestack.com?
I think we need to look at your S3 configuration.

**Comment by velveteer** [comment]
Closing this as it pertains to another codebase.
