### ISSUE TITLE
Getting the following error when i try to open the Filestack picker

### ISSUE THREAD

**Issue by idanb11** [filestack/filestack-js#57]
I'm using the latest version of Filestack js SDK (v0.9.4)
and I'm getting the following error when I try to open the Filestack picker:
```
loader.es2015.js:81 Uncaught TypeError: Cannot read property 'resolvePromise' of undefined
    at Object.registerReadyModule (loader.es2015.js:81)
    at index.js:256
    at index.js:252
registerReadyModule @ loader.es2015.js:81
(anonymous) @ index.js:256
(anonymous) @ index.js:252
```

**Comment by velveteer** [comment]
@idanb11 Can you provide more information like browser and OS?

**Comment by velveteer** [comment]
Using filestack-js 0.9.4 from both npm and the CDN script I am unable to reproduce this error on Chrome 60 on Windows 7. I know where this error is occurring based on your stack trace and the property access on a potentially undefined object was patched in the loader but that version was not added to the picker dependencies. I can bump that and release a patch on 0.9.5 to fix this error. 

However, that the module definition was undefined may be a problem related to your environment. Are you using filestack-js as part of a larger app and/or are you utilizing some kind of async script loading library? Any more information you can provide will be helpful. 

Some information that might help debug:

`registerReadyModule` is called immediately upon execution after the picker script has been injected into the page (after calling `client.pick`), and it looks up a module definition in a global namespace based on the URL of the injected script. If this global is unavailable or manipulated it might cause this logic to fail. It also may fail if other scripts were injected before the picker code executes; this would cause the loader to retrieve the wrong URL and fail to find the module definition.

**Comment by idanb11** [comment]
Thanks @velveteer for your detailed feedback..

Yes, I'm using filestack-js as part of a larger app. 
The Filestack picker is embedded inside a Shopify Store that I'm building.
I can't provide a URL because it is still work-in-progress and includes some private info.
one note regarding this error is that it is not happening in a predictable manner and happens only sometimes (usually it happens if i try to open the Filestack Picker as soon as the page loads).

I agree with your suggestion that it maybe related to that the global is unavailable or manipulated or because other scripts were injected before the picker code executes.

Do you have a debug mode that I can switch on in Filestack js SDK?

**Comment by velveteer** [comment]
@idanb11 No problem, thanks for providing more information. 

There's a debug logger that can be enabled by calling `filestackInternals.logger.on()` in your console, but I don't know how much help it will be. The module definitions are stored on `filestackInternals.loader.modules`. A good idea is to look at the order of script requests on the page, and see if any scripts are being appended to `document.body` after pick is called. The loader looks for the last script in `document.body` and assumes it is the script associated with the module being loaded.

In the meantime I will look into finding a way around what appears to be a race condition in the module loader.

**Comment by velveteer** [comment]
@idanb11 I have pushed a release candidate with a fix for the TypeError mentioned in this issue, and a potential fix to what I believe is the root cause. It's available on npm via `filestack-js@beta` and hosted on our CDN at https://static.filestackapi.com/v3/filestack-0.9.5-rc1.js.

If you have time please try out this release candidate and let us know if it fixes the issue.

**Comment by idanb11** [comment]
Hi @velveteer ,
I'm having hard time to reproduce the Error, So I can't really test the RC with the fix you made...

**Comment by velveteer** [comment]
@idanb11 Here's a reproduction of the bug you reported: https://codepen.io/velveteer/pen/5fec2bc61d30f70b6ec9e7452e6b7fd1

And here is the same code but using 0.9.5-rc1: https://codepen.io/velveteer/pen/7155ca176a5fd976f096dc261531d271

**Comment by idanb11** [comment]
Yes, I can see the error message coming from filestack-js 0.9.4
and that everything works well in the new version filestack-js 0.9.5-rc1..

I'll be happy if you can upgrade the main branch of filestack-js and release the new version as the main production one.

Thanks for you help with this issue @velveteer ...

Idan.,

**Comment by velveteer** [comment]
@idanb11 0.9.5 has been released and contains a patch for this error. Thanks again for reporting this!

**Comment by andrewmartin** [comment]
Still seeing this in a very new version. Any updates?

```
filestack.esm.js?c299:41 Uncaught (in promise) TypeError: i.sent(...) is not a constructor
    at t.eval (filestack.esm.js?c299:41)
    at eval (filestack.esm.js?c299:40)
    at Object.eval [as next] (filestack.esm.js?c299:40)
    at a (filestack.esm.js?c299:40)
```
