### ISSUE TITLE
Upload button is hidden on IE

### ISSUE THREAD

**Issue by wbowling** [filestack/filestack-js#6]
The actions bar is incorrectly aligned on IE causing the upload button to be hidden off to the right:
![image](https://cloud.githubusercontent.com/assets/1418260/24225859/f6cd0a50-0fb6-11e7-97d0-9a9162469f70.png)

We worked around it with the following:
```sass
.fsp-nav
  justify-content: flex-start !important
```

**Comment by velveteer** [comment]
I was able to replicate this in IE11, but only after adding a polyfill for Promise, since right now we aren't claiming to support IE11 in v3. That support is coming, and so we will fix these style issues as well. Thanks for the feedback.

**Comment by velveteer** [comment]
The 0.5.0 release addresses multiple IE11 issues including this one.
