### ISSUE TITLE
Filestack v3 - ability to specify a unique path and name for each file

### ISSUE THREAD

**Issue by evankoehler** [filestack/filestack-js#61]
Currently Filestack defaults to store the file with a unique id, followed by an underscore, followed by the filename. You can specify a path, but on a multi-upload you can only point it to a specific folder. It would be great if there was an option for each file to give it a name to be stored as (such as just a unique id), as well as a location.

If that is not possible, an option to just use the unique id and leave off the automatic appending of the filename would be awesome.

**Comment by celloman** [comment]
bump

**Comment by maryfs** [comment]
Hi,
it will be available in version 3.x.x which will be released soon (2 weeks).
