### ISSUE TITLE
Modifying filename in onFileSelected has no effect

### ISSUE THREAD

**Issue by drphelps** [filestack/filestack-js#62]
**Version: 0.9.9**

The following has no effect on the metadata passed to the `pick()` Promise resolution. I expect the filename(s) to be modified.

```
onFileSelected(file) {
  file.filename = 'foo';
  return file;
},
```

**Comment by velveteer** [comment]
@drphelps Sorry for the confusion, the name modification is achieved using the `file.name` property, which is used internally and converted into `filename` for the external metadata. I should also note this will currently work for local files only.

**Comment by drphelps** [comment]
Thanks for the prompt reply. My fault for misreading the docs.

**Comment by fpereira1** [comment]
> I should also note this will currently work for local files only. 

might be good to updated the readme to include this. I only found out it works for local files only through this comment
