### ISSUE TITLE
mimetypes missing for some MS Office files

### ISSUE THREAD

**Issue by ericvillemure** [filestack/filestack-js#63]
Calling .pick on a .pps file return the following mimetype "application/octet-stream" it should return "application/vnd.ms-powerpoint".  See the following table for all Office file extensions: https://blogs.msdn.microsoft.com/vsofficedeveloper/2008/05/08/office-2007-file-format-mime-types-for-http-content-streaming-2/

**Comment by maryfs** [comment]
Hi, checked on latest version 2.x.x and mimetype is correct.
