### ISSUE TITLE
.txt files are always permitted even when not passed to the pick() accept option

### ISSUE THREAD

**Issue by ericvillemure** [filestack/filestack-js#67]

**Comment by velveteer** [comment]
If a valid value exists for `accept` then it acts as a whitelist for MIME types and extensions. An undefined value for `accept` will allow selection of all files. 

Currently I cannot reproduce this issue with .txt files, but it would be helpful if you can provide your configuration that effectively reproduces this.

**Comment by maryfs** [comment]
Cannot reproduce in v 2.x.x .
