### ISSUE TITLE
options.accept doesn't work as intended with some sources

### ISSUE THREAD

**Issue by NProtagoras** [filestack/filestack-js#68]
For some sources (I've tested Dropbox and Evernote) it is impossible to upload files even though they are allowed via option.accept.

for example: 
options = {
fromSources: dropbox
accept: ['audio/mp3', 'audio/aac', 'audio/ogg']
}

**expected behavior**: all files that are of the above accepted mimetypes will be available to pick.
**actual behavior**: only .ogg and .mp3 files are available, .aac are rejected with the following error: 

> File example.aac is not an accepted file type. The accepted file types are audio/mp3,audio/aac,audio/ogg

_additional info_:
The same issue also happens on EverNotes that contain audio files (both .aac and .ogg are rejected).
When options.accept is not provided (undefined), the files are available to be picked, and the received filesUploaded have the right mimetype.

**Comment by velveteer** [comment]
This is likely a problem with cloud drives reporting inaccurate MIME types. I tested an AAC file in Dropbox and was unable to retrieve a valid MIME type from the folder list response.

You may want to try using the extension format (e.g. `accept: [ '.aac', ... ]` alongside the MIME format to handle this problem. I will follow up with our cloud API team and see if there is anything we can do to ensure that MIME types are being returned correctly.

**Comment by NProtagoras** [comment]
the extension format does the trick, thanks :)
