### ISSUE TITLE
Connecting to googleDrive fails on OAUTH redirect issue

### ISSUE THREAD

**Issue by NProtagoras** [filestack/filestack-js#69]
How to reproduce:

1. Try to connect to googleDrive via filestack-js (see image #1)
![filestack_google_loginrequest](https://user-images.githubusercontent.com/32260168/33175358-33ec2042-d064-11e7-9277-e904faf5876e.PNG)

2. receive error from google about "redirect_uri_mismatch"
![filestack_googleoauth_bug](https://user-images.githubusercontent.com/32260168/33175357-33c7af50-d064-11e7-94a9-276ebe831b05.PNG)

**Comment by NProtagoras** [comment]
seems to have been resolved over the weekend.

**Comment by NProtagoras** [comment]
actually, my bad. The auth token works fine for v2, but on v3 I still get the same error.

**Comment by velveteer** [comment]
@NProtagoras Are you still seeing this issue? If so can you provide browser information so we can reproduce it?

**Comment by NProtagoras** [comment]
seems like it was just an issue with our config using a wrong key - nothing to do with filestack. 

Thanks for the response!
