### ISSUE TITLE
Configurable source header in Pick 

### ISSUE THREAD

**Issue by SteveJamiesonSSN** [filestack/filestack-js#73]
Is it possible to have a way to configure the selected source header (text/icon) ?
[https://imgur.com/9p1q9YK](url)
![sourceheader](https://user-images.githubusercontent.com/26970903/33615318-3d1919f4-d9b0-11e7-9559-65c215ae65d4.png)

or at least keep a common uniform look when switching sources 
i.e My device - header shows icon and text of the same ? 
i.e Web Search - header shows icon and text of the same ?  

Facebook - seems to show a icon of the selected source in the header.

**Comment by velveteer** [comment]
There's no explicit option for this besides modifying the CSS for these elements. However I believe nobody will be opposed to keeping the header element consistent, so I will mark this as a design enhancement.

**Comment by velveteer** [comment]
The latest version of the picker should be using icons for all source headers. This can be changed trivially with some custom CSS, and text is also now configurable using the `customText` option: https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#customtext
