### ISSUE TITLE
Unable to log in into Google Drive after `client.logout()` method called

### ISSUE THREAD

**Issue by krosvi** [filestack/filestack-js#75]
Unable to log in back into Google Drive after call `client.logout()`
[Link to Codepen](https://codepen.io/anon/pen/XzwbzQ)

## Steps to reproduce
1. Initialize Filestack client.
2. Open file dialog and connect to Google Drive. Allow to connect.
3. Close file dialog and call log out [client.logout()](https://github.com/filestack/filestack-js#module_filestack..init.logout)
4. Open file dialog again and click to connect to Google Drive button. Allow to connect.

## Expected result
After redirect, file dialog window should show users files.

## Actual result
After redirect, file dialog window shows message that you need to authenticate with Google Drive.

**Comment by lukanus** [comment]
Hello @krosvi. I'm one of the filestack's backend engineers. There was a discrepancy between the way we handle some cookies. It was changed, so your code should work without any changes (no longer occur using given codepen).
