### ISSUE TITLE
Regression: Setting pick timeout doesn't work in 0.10.0

### ISSUE THREAD

**Issue by wuservices** [filestack/filestack-js#78]
Before 0.10.0, I was able to set a really low pick timeout like 1000 ms to simulate network issues to test the behavior of the uploader.

However, after updating to 0.10.0, setting a low timeout doesn't do anything. onRetry is never called, and the PUT requests are never canceled. Previously we'd see that all the PUT requests were canceled after 1 second. I just reverted back to 0.9.12 with the same code, and verified that the same settings do work as expected with the older code.

**Comment by velveteer** [comment]
@wuservices Good catch, this is a confirmed regression. I will have a patch out for this soon. Thanks for reporting!

**Comment by wuservices** [comment]
@velveteer do you think you'll be able to release a fix this week?

Until then, do you know what the expected timeout behavior is? Is there a fixed number it's using, or is there no timeout?

Now that we have some good analytics in place, we're eager to test out some performance tweaks to see how we can improve things.

Thanks!

**Comment by velveteer** [comment]
@wuservices Hey sorry for the delay. I made a patch to fix the `uploadConfig.timeout` regression, and it's now available in 0.10.1.

**Comment by wuservices** [comment]
Thank you! This feels a lot better, can't wait to see how it does on real users.
