### ISSUE TITLE
Cropped Image is not return by file picker

### ISSUE THREAD

**Issue by deliriousrhino** [filestack/filestack-js#81]
filestack-js 0.10.1

When I call
`fsClient.pick({
            fromSources: ["local_file_system", "url", "facebook", "instagram", "googledrive", "dropbox", "evernote", "flickr"],
            maxSize: 102400000,
            maxFiles: 1,
            minFiles: 1,
            transformations: {
                crop: {
                    force: true,
                    aspectRatio: 1.778
                },
                rotate: true
            },
            accept: ["image/*"]
        }).then(this.imageUploaded);`

`imageUploaded({ filesUploaded, filesFailed }) {
       
        const { onChange } = this.props;
        if (filesFailed.length) {
            message.error('Image failed to upload');
            return;
        }
        console.log(filesUploaded)
}`

The file that is returned is not the cropped image but rather the full image that was selected

Steps

1. Crop
<img width="760" alt="screen shot 2017-12-18 at 10 50 00 am" src="https://user-images.githubusercontent.com/644511/34085229-5017468a-e3e1-11e7-9062-f440e2664cfb.png">

2. Upload
<img width="756" alt="screen shot 2017-12-18 at 10 50 05 am" src="https://user-images.githubusercontent.com/644511/34085228-4fe8af8c-e3e1-11e7-884c-b1ad0a0c08d2.png">

See the result here 
https://cdn.filestackcontent.com/w6LGhDJ6QAupRylsjQnT

Upload Id "cdf9eb61cb1aeb87c781af10291c1c97"

**Comment by velveteer** [comment]
@deliriousrhino I am not entirely certain but this might be a bug with the background uploading. Can you pass `uploadInBackground: false` and confirm if this behavior persists?

**Comment by deliriousrhino** [comment]
Yes when I add uploadInBackground: false the issue is fixed

**Comment by velveteer** [comment]
Alright, so then we know what we need to patch here. Thanks for reporting this! We will update this issue once the bug has been fixed in a patch release.

**Comment by pcholuj** [comment]
Hi, this is fixed in newer releases.
