### ISSUE TITLE
Filestack package treats base64 string as blob, then fails

### ISSUE THREAD

**Issue by Rawne** [filestack/filestack-js#86]
When sending a valid base64 string to the filestack.upload function, i am getting 

> Failed to execute 'readAsArrayBuffer' on
>             'FileReader': parameter 1 is not of type 'Blob'

Which surprises me, because i am not sending it as a blob, so i dont think it should even try this, this makes me think it's not detecting the type correctly? 

I am using the package in ionic, running on android.

**Comment by velveteer** [comment]
@Rawne Thanks for reporting this. Can you help by providing an example base64 string that is failing? The uploader actually converts base64 into a blob in the background, so it looks like something is failing during that process.

**Comment by Rawne** [comment]
This is my base64 string just before sending it to the upload function: https://gist.github.com/Rawne/3a733210a9fcd269337a8a79b2e82962

Weird thing is, i checked out a fresh repo from the same codebase, rebuilt ionic, and things worked as expected again. Maybe there is some weird stuff going on with ionic, perhaps changing global js functions or something, which interferes with the filestack code?
