### ISSUE TITLE
Please add a typescript definition file

### ISSUE THREAD

**Issue by niemyjski** [filestack/filestack-js#87]
This would make it much easier to use your api with full intellisence.

**Comment by velveteer** [comment]
@niemyjski There is a full Typescript rewrite on its way, but I have no ETA for the release. It's a top priority, and I will update this issue when that work is published.

**Comment by niemyjski** [comment]
In the mean time, how up to date is this: https://github.com/filestack/filestack-js/blob/typings/types/index.d.ts ?

**Comment by niemyjski** [comment]
Guess it's not perfect as init is missing the cname overload: https://github.com/filestack/filestack-js/blob/typings/types/index.d.ts#L8

**Comment by velveteer** [comment]
This should be resolved in 1.0.0-rc1. Please see the release notes here: https://github.com/filestack/filestack-js/issues/101. 

If you feel this issue should be reopened please let us know.

**Comment by jologz** [comment]
For those that are using both javascript and typescript, I've created filestack typings here based on their interfaces in each typescript file. https://github.com/jologz/filestack.d.ts
