### ISSUE TITLE
Any way to export files?

### ISSUE THREAD

**Issue by niemyjski** [filestack/filestack-js#88]
In v2 there was a way to export files via

```js
filepicker.exportFile(url,
      {
        container: 'modal',
        suggestedFilename: fileName,
      },
      blob => {
        console.log(blob);
      },
      error => {
        console.log(error);
      });
```

Is there any good way to do this in the new api?

**Comment by niemyjski** [comment]
The readme isn't very up-to-date with your v3 api docs, and vise versa (the api docs have way more information but don't tell you what returns a promise)

This can be done via `this.client.retrieve(attachment.id, { dl: true });`

**Comment by stvpalumbo** [comment]
@niemyjski my team has the same issue, we weren't able to figure out how get the filestack client dialog to trigger using `client.retrieve` using V3. It would only return the bytearray.

My users like the ability to export files directly to drop box, google drive, etc...

**Comment by niemyjski** [comment]
@stvpalumbo you can do this really easy as it returns a Blob object by passing it to filesaver.js (https://github.com/eligrey/FileSaver.js)

```js
saveAs(await this.client.retrieve(attachment.id, { dl: true }), 'filename.jpg')
```

**Comment by stvpalumbo** [comment]
@niemyjski thanks for the library recommendation, I'll check it out!

**Comment by maryfs** [comment]
Hi,
we don't have export file in v3.

**Comment by raf66** [comment]
I see "Planned" back in May 2019.  It's now May 2020.  Any progress on this feature request?
