### ISSUE TITLE
Please release source code

### ISSUE THREAD

**Issue by niemyjski** [filestack/filestack-js#89]
Please take open source seriously and release the unminified source that can be found in the dist folder. I want to debug code that is running and contribute back / help me with porting code to .net. You don't make it easy and your api docs need much love.

**Comment by velveteer** [comment]
@niemyjski Thanks for the feedback. We plan on releasing a 1.0 of this SDK sometime in Q1, which will open-source the client, but the picker UI will remain closed-source (this may change eventually). All of our other client libraries are open-source, so this one will simply be following suit. We have a little more work to do before a release candidate is ready, but when it is I will make that code available with an Apache 2 license.

**Comment by velveteer** [comment]
This repo is now open sourced under the Apache 2.0 license. Thank you for being patient!

**Comment by niemyjski** [comment]
Thanks!!

**Comment by niemyjski** [comment]
Curious are you having users sign a cla?

**Comment by velveteer** [comment]
At the moment we have no CLA for this codebase or any of our other open-source libraries.
