### ISSUE TITLE
pick() callback for modal close via X button.

### ISSUE THREAD

**Issue by fabrizio5680** [filestack/filestack-js#9]
v2 of api would trigger callback if modal was closed via X. This allowed handling of pick dismissal.

Will v3 handle this situation, or is there a way to handle this currently that is not documented.

**Comment by velveteer** [comment]
There's no callback for picker close yet, but I will prioritize it for an upcoming release, especially since #7 has brought it up as well.

**Comment by velveteer** [comment]
@fabrizio5680 0.6.0 has added the `onClose` callback to the picker.

**Comment by bcinman** [comment]
It looks like the `onClose` callback that was introduced is called every time the picker is closed. Whether by clicking the X or by a successful `pick()`. I think this issue was for a callback that only gets called when the user manually X's out of the picker.

**Comment by velveteer** [comment]
@bcinman Ah I see. I will go ahead and reopen this. Would something like `onManualClose` make more sense for this behavior?

**Comment by bcinman** [comment]
Yeah I think so, or maybe `onCancel`.

**Comment by velveteer** [comment]
0.8.0 introduces a new option called `rejectOnCancel` if you prefer to capture the cancel event. This is different from `onClose` since it will only reject the Promise on "cancel", e.g. clicking the close button or hitting ESC.
