### ISSUE TITLE
Upload progress bar is not working

### ISSUE THREAD

**Issue by deliriousrhino** [filestack/filestack-js#94]
Using version 0.11.2.

The progress bar is not working it says at 0% the the file just completes
<img width="639" alt="screen shot 2018-03-01 at 12 13 03 pm" src="https://user-images.githubusercontent.com/644511/36822049-28081938-1d4a-11e8-9d3e-e1ee4896e8b7.png">

**Comment by maryfs** [comment]
Hi, problem is resolved in newer versions.
