### ISSUE TITLE
allow accept option to be undefined

### ISSUE THREAD

**Issue by slipdef** [filestack/filestack-js#95]
If I pass accept option as undefined I get a validation exception from filepicker. I understand from another answer that I should omit the accept option altogether to be able to upload any file. I get it, but guys, what a shame? I bet you won't find any good public js API that forces such a strange policy. Just check it for undefined.

Here is my code:
![image](https://user-images.githubusercontent.com/4365327/36925865-7f831eca-1ea7-11e8-879c-8ba94ed02750.png)

I need to declare a variable to be able to omit the accept key conditionally.

**Comment by pcholuj** [comment]
Fixed in 3.0.0
