### ISSUE TITLE
storeTo path option duplicates on result.

### ISSUE THREAD

**Issue by Focusnik** [filestack/filestack-js#96]
Hey guys. I have to provide storeTo options to pick, like this:

`this.client.pick(this.options).then(result => this.processFiles(result));`

the structure of storeTo section in options is:

`storeTo:Object
   container:"simpliv-user-resources-production"
   location:"s3"
   path:"test_videos/"
   region:"eu-central-1"`

But when i receive a webhook from filestack, i see this:
`array (
  'id' => 29543672,
  'action' => 'fp.upload',
  'timestamp' => 1520460723,
  'text' =>
  array (
    'container' => 'simpliv-user-resources-production',
    'url' => 'https://cdn.filestackcontent.com/OaD4KMP2Rz2Lyaah1df8',
    'filename' => 'videoplayback.mp4',
    'client' => 'Computer',
    'key' => 'test_videos/test_videos/mPYD16jRSeKXqQPSIe8L_videoplayback.mp4',
    'type' => 'video/mp4',
    'status' => 'Stored',
    'size' => 2504427,
  ),
)`

as you can see, KEY value duplicates the path option. And on my s3 bucket a get double folders one in one and then file. What i do wrong?

**Comment by velveteer** [comment]
If you need more help with configuring the S3 storage backend please reach out to our support team by emailing support@filestack.com. This doesn't appear to be an issue with this library so it will be closed.
