### ISSUE TITLE
cname not being used in preview

### ISSUE THREAD

**Issue by iplukens** [filestack/filestack-js#99]
Currently the preview method isn't using the cname.  Even with one set up, it still connects to `cdn.filestackcontent.com` + `assets.filestackapi.com`

Maybe a new feature, but since the cname is specified at the client level, I would expect it to be used for every method.

**Comment by velveteer** [comment]
This should be resolved in 1.0.0-rc1. Please see the release notes here: https://github.com/filestack/filestack-js/issues/101. 

If you feel this issue should be reopened please let us know.
